---
- name: disable apache sites
  command: a2dissite {{ product_name }}-ui
  ignore_errors: true
  become: true

- name: disable apache modules (due to a bug with php mod not properly getting purged)
  apache2_module: state=absent name={{ item }}
  loop: "{{ apache2_required_modules }}"
  ignore_errors: true
  become: true

- name: uninstall all packages for {{ product_name }}, keeping git and ansible
  package:
    state: absent
    name: "{{ item }}"
    purge: true
  loop:
    - rsyslog
    - "{{ webserver_package_name }}"
    - gnupg2
    - apt-transport-https
    - software-properties-common
    - npm
    - python3-pip
    - python3-virtualenv
    - python3-psycopg2
    - "{{ postgresql_c_client_library_header_files }}"
    - "{{ postgresql_package }}"
    - "{{ postgresql_c_client_library_header_files }}"
    - postgresql-client
    - ldap-utils
    - libldap-common
    - libldap
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - "dotnet-sdk-{{ dotnet_version }}"
    - make
    - "{{ postgresql_dev_package }}"
    - "{{ postgresql_test_package }}"
    - "{{ webserver_package_name }}"
  when: wipe_packages is defined and wipe_packages|bool
  become: true

- name: uninstall openldap on Debian
  package:
    state: absent
    name: slapd
    purge: yes
  become: true
