secret:
  ignored-paths:
    - "**/test_*"
    - "roles/tests-unit/**"
    - "roles/tests-integration/**"

# ignore all test files, as they may contain test credentials that are not used in production and should not be flagged by GitGuardian.
