class ImportStatistics:
    network_object_add_count: int = 0
    network_object_delete_count: int = 0
    network_object_change_count: int = 0
    service_object_add_count: int = 0
    service_object_delete_count: int = 0
    service_object_change_count: int = 0
    user_object_add_count: int = 0
    user_object_delete_count: int = 0
    user_object_change_count: int = 0
    zone_object_add_count: int = 0
    zone_object_delete_count: int = 0
    zone_object_change_count: int = 0
    rule_add_count: int = 0
    rule_delete_count: int = 0
    rule_change_count: int = 0
    rule_move_count: int = 0  # when a rule is moved within the same rulebase
    rulebase_add_count: int = 0
    rulebase_change_count: int = 0
    rulebase_delete_count: int = 0
    rule_enforce_change_count: int = 0
    rulebase_link_add_count: int = 0
    rulebase_link_change_count: int = 0
    rulebase_link_delete_count: int = 0
