class ImportStatistics:
    network_object_add_count: int = 0
    network_object_delete_count: int = 0
    network_object_change_count: int = 0
    service_object_add_count: int = 0
    service_object_delete_count: int = 0
    service_object_change_count: int = 0
    user_object_add_count: int = 0
    user_object_delete_count: int = 0
    user_object_change_count: int = 0
    zone_object_add_count: int = 0
    zone_object_delete_count: int = 0
    time_object_add_count: int = 0
    time_object_delete_count: int = 0
    time_object_change_count: int = 0
    rule_add_count: int = 0
    rule_delete_count: int = 0
    rule_change_count: int = 0
    rule_move_count: int = 0  # when a rule is moved. implies rule_change_count
    rule_ref_add_count: int = 0  # e.g. rule_to, rule_nwobj_resolved, rule_enforced_on_gateway
    rule_ref_delete_count: int = 0
    rulebase_add_count: int = 0
    rulebase_change_count: int = 0
    rulebase_delete_count: int = 0
    rulebase_link_add_count: int = 0
    rulebase_link_delete_count: int = 0
    inconsistent_nwobj_delete_count: int = 0
    inconsistent_svcobj_delete_count: int = 0
    inconsistent_userobj_delete_count: int = 0
    inconsistent_rule_delete_count: int = 0
    inconsistent_rulebase_link_delete_count: int = 0
    inconsistent_ref_delete_count: int = 0
