# If you want to use distributed installation, follow the steps on localhost
# 1. ssh-keygen -t rsa
# Press enter for each line 
# 2. cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# 3. chmod og-wx ~/.ssh/authorized_keys
# 4. ssh-copy-id <user>@<remote-server>
# 5. add remote servers below

all:
  hosts:
    localhost:
      ip_address: 127.0.0.1
      ansible_connection: local
#   Add servers for distributed installation here. Use these servers in the children dictionary below.
#    ui-srv:
#      ansible_connection: ssh
#      ansible_host: 192.168.2.3
  children:

    frontends:
      hosts:
        localhost:

    # only one databaseserver should exist
    databaseserver:
      hosts:
        localhost:

    # only one apiserver should exist
    apiserver:
      hosts:
        localhost:

    importers:
      hosts:
        localhost:

    # only one middlewareserver should exist
    middlewareserver:
      hosts:
        localhost:

    # only one sampleserver should exist
    sampleserver:
      hosts:
        localhost:

    testservers:
      hosts:
        localhost:

    # only one logserver should exist
    logserver:
      hosts:
        localhost:
