query searchNetworkServicesForRequestByPort(
  $mgmId: Int!
  $svcTypeIds: [Int!]!
  $port: Int!
  $limit: Int!
) {
  firewall_nw_service(
    where: {
      mgm_id: { _eq: $mgmId }
      svc_typ_id: { _in: $svcTypeIds }
      active: { _eq: true }
      removed: { _is_null: true }
      svc_port: { _lte: $port }
      _or: [
        { svc_port_end: { _gte: $port } }
        { _and: [{ svc_port_end: { _is_null: true } }, { svc_port: { _eq: $port } }] }
      ]
    }
    order_by: [{ svc_name: asc }, { svc_id: asc }]
    limit: $limit
  ) {
    svc_id
    svc_name
    ip_proto_id
    svc_port
    svc_port_end
  }
}
