# client tools (ldapmodify, ldapdelete, ldapsearch) are needed in every installation mode,
# so they are installed separately from the server packages
openldap_client_pkgs:
  - ldap-utils

openldap_server_pkgs:
  - slapd
  - openssl
  - python3-openssl

openldap_server_app_path: "/etc/ldap"
openldap_server_user: "openldap"
openldap_schema_dir: "/etc/ldap/schema"
openldap_module_path: "/usr/lib/ldap"
openldap_service_defaults_file: "/etc/default/slapd"
