- block: 

  - name: restart docker
    systemd:
      name: docker
      daemon_reload: yes
      state: restarted
    become: yes
    listen: "docker"

  # - name: Reload service systemctl
  #   systemd:
  #     daemon_reload: yes
  #   listen: "restart daemons"
  
  # - name: restart service docker
  #   service:
  #     name: docker
  #     state: restarted
  #   listen: "restart docker service"

  become: yes
  
  