- block:
    - name: add user sampledev
      user:
        name: "{{ sample_config_user }}"
        comment: fworch import user for sample configs
        home: "{{ sample_config_user_home }}"
        shell: /bin/bash
        group: "{{ fworch_group }}"
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"

    - name: slurp sample-data user pub key
      slurp:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub"
      register: user_pub_key

    - name: add sample-data user pub key to its authorized_keys
      lineinfile:
        path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
        line: "{{ user_pub_key['content'] | b64decode | trim }}"
        create: true
        state: present
        regex: "ansible-generated"

    - name: correct sample-data users authorized_keys file permissions
      file:
        path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
        owner: "{{ sample_config_user }}"
        mode: "0600"

    - name: fetch sample-data user pub key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub"
        dest: "/tmp/"

    - name: fetch sample-data user priv key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"
        dest: "/tmp/"

    - name: copy sample configs
      copy:
        src: "sample-configs"
        dest: "{{ sample_config_user_home }}"
        owner: "{{ sample_config_user }}"
        group: "{{ fworch_group }}"

  become: true
  