- block:
    - name: copy config changes scripts
      copy:
        src: "config_changes"
        dest: "{{ sample_config_user_home }}"
        owner: "{{ sample_config_user }}"
        group: "{{ fworch_group }}"

    - name: Executes write_date_to_comment.py as cronjob in /etc/cron.d
      cron:
        name: change fw config with write_date_to_comment.py
        weekday: "*"
        minute: "0"
        hour: "*"
        user: "{{ sample_config_user }}"
        job: "python3 {{ sample_config_user_home }}/config_changes/write_date_to_comment.py"
        cron_file: "{{ product_name }}_sample_data_write_date_to_comment"

    - name: Executes many enlarge_rule.py as cronjob in /etc/cron.d
      cron:
        name: change fw config with enlarge_rule.py {{ item }}
        weekday: "*"
        minute: "{{ item }}"
        hour: "*"
        user: "{{ sample_config_user }}"
        job: "python3 {{ sample_config_user_home }}/config_changes/enlarge_rule.py {{ item }}"
        cron_file: "{{ product_name }}_sample_data_enlarge_rule_{{ item }}"
      with_sequence: start=3 end=59 stride=1
      when: "sample_data_rate == 'high'"

    - name: Executes enlarge_rule.py as cronjob in /etc/cron.d
      cron:
        name: change fw config with enlarge_rule.py
        weekday: "*"
        minute: "1"
        hour: "*"
        user: "{{ sample_config_user }}"
        job: "python3 {{ sample_config_user_home }}/config_changes/enlarge_rule.py"
        cron_file: "{{ product_name }}_sample_data_enlarge_rule"
      when: "sample_data_rate != 'high'"

  become: true
