# add ro db user pwd file

- name: Check if marker file exists
  stat:
    path: "{{ fwo_db_ro_user_password_file }}"
  register: fwo_db_ro_pwd_file
  become: true

- block:
    - name: set {{ fwo_db_ro_user }} password randomly
      set_fact:
        fwo_db_ro_pwd: "{{ randomly_generated_pwd }}"

    - name: write {{ fwo_db_ro_user }} password to secrets directory
      copy:
        content: "{{ fwo_db_ro_pwd }}\n"
        dest: "{{ fwo_db_ro_user_password_file }}"
        mode: '0600'
        owner: "{{ fworch_user }}"
        group: "{{ fworch_group }}"
      become: true
      become_user: root

  when: not fwo_db_ro_pwd_file.stat.exists
