- name: set link to debian cert store
  file:
    src: "{{ openssl_cert }}"
    dest: /usr/local/share/ca-certificates/{{ product_name }}-server.crt
    state: link
  become: true

- name: reconfigure ca-certificates package
  debconf:
    name: ca-certificates
  become: true
