using Newtonsoft.Json;
using System.Text.Json.Serialization;

namespace FWO.Data
{
    /// <summary>
    /// JSON envelope generated by a log data customization script.
    /// </summary>
    public class LogDataImportFile
    {
        [JsonProperty("logs"), JsonPropertyName("logs")]
        public List<LogDataImportEntry> Logs { get; set; } = new();
    }

    /// <summary>
    /// One log entry in the customization-script JSON contract.
    /// </summary>
    public class LogDataImportEntry
    {
        [JsonProperty("app_id"), JsonPropertyName("app_id")]
        public string AppId { get; set; } = "";

        [JsonProperty("log_count"), JsonPropertyName("log_count")]
        public int LogCount { get; set; }

        [JsonProperty("source"), JsonPropertyName("source")]
        public string Source { get; set; } = "";

        [JsonProperty("destination"), JsonPropertyName("destination")]
        public string Destination { get; set; } = "";

        [JsonProperty("protocol"), JsonPropertyName("protocol")]
        public int? Protocol { get; set; }

        [JsonProperty("port"), JsonPropertyName("port")]
        public int? Port { get; set; }

        [JsonProperty("action"), JsonPropertyName("action")]
        public string? Action { get; set; }

        [JsonProperty("log_time"), JsonPropertyName("log_time")]
        public DateTimeOffset? LogTime { get; set; }

        [JsonProperty("rule_name"), JsonPropertyName("rule_name")]
        public string? RuleName { get; set; }
    }

    /// <summary>
    /// Validated data used for inserting a logging entry through GraphQL.
    /// </summary>
    public class FirewallLogEntryInput : FirewallLogEntry
    {
        [JsonProperty("owner_id"), JsonPropertyName("owner_id")]
        public int OwnerId { get; set; }
    }
}
