---
- block:

    - name: add {{ fworchtest_user }} user
      user:
        name: "{{ fworchtest_user }}"
        shell: /bin/bash
        home: "{{ fworchtest_home }}"
        state: present
        group: "{{ fworch_group }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa     
        comment: "{{ product_name }} test user for webhook github integration"

    - name: give {{ fworchtest_user }} user full sudo access without pwd for webhook automation
      lineinfile:
        path: /etc/sudoers
        line: "{{ fworchtest_user }} ALL=(ALL) NOPASSWD:ALL"

    # ansible is needed for running auto install on the fwo host itself
    - name: Install packages for webhook receiver
      package:
        name: "{{ item }}"
      loop:
        - python3-flask
        - ansible
        
    - name: create webhook dir {{ fworchtest_home }}/webhook
      file:
        dest: "{{ fworchtest_home }}/webhook"
        state: directory
        owner: "{{ fworchtest_user }}"
        group: "{{ fworch_group }}"
        mode: "0775"

    - name: copy startup file from template
      template:
        src: fworch-webhook-receiver.service.j2
        dest: "/lib/systemd/system/fworch-webhook-receiver.service"
        mode: "0755"
      notify: "restart daemons"

    - name: copy webhook file from template
      template:
        src: fworch-webhook-receiver.py.j2
        dest: "{{ fworchtest_home }}/fworch-webhook-receiver.py"
        mode: "0755"
      notify: "restart daemons"

    - name: make webhook run at host startup
      systemd:
        name: fworch-webhook-receiver
        enabled: yes

    - name: start webhook
      systemd:
        name: fworch-webhook-receiver
        state: restarted

    - name: create webhook secret file
      lineinfile:
        path: "{{ fworchtest_home }}/fworch-webhook.secret"
        line: "{{ webhook_secret }}"
        create: yes
        backup: yes
        mode: 0600
        owner: "{{ fworchtest_user }}"
        group: "{{ fworch_group }}"

    - name: create fworchtest gitconfig file
      blockinfile:
        path: "{{ fworchtest_home }}/.gitconfig"
        block: |
          [http]
            proxy = {{ http_proxy }}
          [https]
            proxy = {{ http_proxy }}
        create: yes
        backup: yes
        mode: 0644
        owner: "{{ fworchtest_user }}"
        group: "{{ fworch_group }}"

  become: yes
