-- $Id: iso-grants.sql,v 1.1.2.2 2007-12-13 10:47:32 tim Exp $
-- $Source: /home/cvs/iso/package/install/database/Attic/iso-grants.sql,v $
-- GRANTS on sequences
GRANT SELECT ON TABLE import_changelog_seq TO public;
GRANT SELECT ON TABLE change_type_change_type_id_seq TO public;
GRANT SELECT ON TABLE abs_change_id_seq TO public;
GRANT SELECT ON TABLE client_client_id_seq TO public;
GRANT SELECT ON TABLE client_network_client_net_id_seq TO public;
GRANT SELECT ON TABLE device_dev_id_seq TO public;
GRANT SELECT ON TABLE error_log_error_log_id_seq TO public;
GRANT SELECT ON TABLE import_control_id_seq TO public;
GRANT SELECT ON TABLE import_object_obj_id_seq TO public;
GRANT SELECT ON TABLE import_rule_rule_id_seq TO public;
GRANT SELECT ON TABLE import_user_user_id_seq TO public;
GRANT SELECT ON TABLE log_obj_seq TO public;
GRANT SELECT ON TABLE log_rule_seq TO public;
GRANT SELECT ON TABLE log_svc_seq TO public;
GRANT SELECT ON TABLE log_usr_seq TO public;
GRANT SELECT ON TABLE management_mgm_id_seq TO public;
GRANT SELECT ON TABLE object_obj_id_seq TO public;
GRANT SELECT ON TABLE request_request_id_seq TO public;
GRANT SELECT ON TABLE rule_from_rule_from_id_seq TO public;
GRANT SELECT, UPDATE ON TABLE report_report_id_seq TO public;
-- GRANT SELECT ON TABLE rule_head_rule_head_id_seq TO public;
GRANT SELECT ON TABLE rule_rule_id_seq TO public;
GRANT SELECT ON TABLE services_srv_id_seq TO public;
GRANT SELECT ON TABLE stm_action_action_id_seq TO public;
GRANT SELECT ON TABLE stm_color_stm_color_id_seq TO public;
GRANT SELECT ON TABLE stm_dev_typ_dev_typ_id_seq TO public;
GRANT SELECT ON TABLE stm_nattyp_nattyp_id_seq TO public;
GRANT SELECT ON TABLE stm_obj_typ_obj_typ_id_seq TO public;
GRANT SELECT ON TABLE stm_report_typ_report_typ_id_seq TO public;
GRANT SELECT ON TABLE stm_track_track_id_seq TO public;
GRANT SELECT ON TABLE usr_user_id_seq TO public;
GRANT SELECT ON TABLE zone_zone_id_seq TO public;
GRANT SELECT ON TABLE client_username_client_username_id_seq TO public;

GRANT UPDATE ON TABLE import_changelog_seq TO public;
GRANT UPDATE ON TABLE change_type_change_type_id_seq TO public;
GRANT UPDATE ON TABLE abs_change_id_seq TO public;
GRANT UPDATE ON TABLE client_client_id_seq TO public;
GRANT UPDATE ON TABLE client_network_client_net_id_seq TO public;
GRANT UPDATE ON TABLE device_dev_id_seq TO public;
GRANT UPDATE ON TABLE error_log_error_log_id_seq TO public;
GRANT UPDATE ON TABLE import_control_id_seq TO public;
GRANT UPDATE ON TABLE import_object_obj_id_seq TO public;
GRANT UPDATE ON TABLE import_rule_rule_id_seq TO public;
GRANT UPDATE ON TABLE import_user_user_id_seq TO public;
GRANT UPDATE ON TABLE log_obj_seq TO public;
GRANT UPDATE ON TABLE log_rule_seq TO public;
GRANT UPDATE ON TABLE log_svc_seq TO public;
GRANT UPDATE ON TABLE log_usr_seq TO public;
GRANT UPDATE ON TABLE management_mgm_id_seq TO public;
GRANT UPDATE ON TABLE object_obj_id_seq TO public;
GRANT UPDATE ON TABLE request_request_id_seq TO public;
GRANT UPDATE ON TABLE rule_from_rule_from_id_seq TO public;
-- GRANT UPDATE ON TABLE rule_head_rule_head_id_seq TO public;
GRANT UPDATE ON TABLE rule_rule_id_seq TO public;
GRANT UPDATE ON TABLE services_srv_id_seq TO public;
GRANT UPDATE ON TABLE stm_action_action_id_seq TO public;
GRANT UPDATE ON TABLE stm_color_stm_color_id_seq TO public;
GRANT UPDATE ON TABLE stm_dev_typ_dev_typ_id_seq TO public;
GRANT UPDATE ON TABLE stm_nattyp_nattyp_id_seq TO public;
GRANT UPDATE ON TABLE stm_obj_typ_obj_typ_id_seq TO public;
GRANT UPDATE ON TABLE stm_report_typ_report_typ_id_seq TO public;
GRANT UPDATE ON TABLE stm_track_track_id_seq TO public;
GRANT UPDATE ON TABLE usr_user_id_seq TO public;
GRANT UPDATE ON TABLE zone_zone_id_seq TO public;
GRANT UPDATE ON TABLE client_username_client_username_id_seq TO public;
GRANT SELECT ON TABLE text_msg TO configimporters;
GRANT SELECT ON TABLE text_msg TO dbbackupusers;

