---
- name: Create universal ldif directory
  file:
      path: "{{ middleware_ldif_dir }}"
      state: directory
      owner: "{{ fworch_user }}"
      group: "{{ fworch_group }}"
  become: true
  tags: ["test", "integrationtests"]

- block:
      ### OS basics
      - name: Add the OS specific varibles
        include_vars: "{{ ansible_os_family }}.yml"

      - name: Install the openldap and required Packages
        package:
            name: "{{ item }}"
            state: present
        loop: "{{ openldap_server_pkgs }}"

      - name: Create directory for ldap pid
        file:
            path: "/var/run/slapd"
            state: directory
            owner: "{{ openldap_server_user }}"
            group: "{{ openldap_server_user }}"

      ### Root password
      - name: Check if manager password exist
        stat:
            path: "{{ ldap_manager_pwd_file }}"
        register: is_manger_pw_present_flag

      - name: Decide on random manager password
        set_fact:
            openldap_server_random_rootpw: "{{ randomly_generated_pwd }}"
        when: not is_manger_pw_present_flag.stat.exists

      - name: Write random manager password to file
        copy:
            content: "{{ openldap_server_random_rootpw }}"
            dest: "{{ ldap_manager_pwd_file }}"
            mode: "0600"
            owner: "{{ fworch_user }}"
            group: "{{ fworch_group }}"
        when: not is_manger_pw_present_flag.stat.exists
        tags: ["test"]

      - name: Generate the root password hash for the config
        command: "slappasswd -T {{ ldap_manager_pwd_file }}"
        register: root_password

      ### TLS
      - name: Create ldap certificates
        include_role:
            name: openssl-cert
        vars:
            openssl_cert_path: "{{ openldap_server_cert_path }}"
            openssl_user: "{{ openldap_server_user }}"
            openssl_private_key: "{{ openldap_server_private_key }}"
            openssl_csr: "{{ openldap_server_csr }}"
            openssl_country: "{{ openldap_server_country }}"
            openssl_state: "{{ openldap_server_state }}"
            openssl_location: "{{ openldap_server_location }}"
            openssl_organization: "{{ openldap_server_organization }}"
            openssl_email_address: "{{ openldap_server_email_address }}"
            openssl_cert: "{{ openldap_server_cert }}"

      ### Config files
      - name: Create the directory for ldap database
        file:
            path: "/var/lib/ldap/{{ openldap_server_domain_name }}/"
            state: directory
            owner: "{{ openldap_server_user }}"
            group: "{{ openldap_server_user }}"

      - name: Create the DB_CONFIG file
        copy:
            src: DB_CONFIG
            dest: /var/lib/ldap/{{ openldap_server_domain_name }}/DB_CONFIG
            owner: "{{ openldap_server_user }}"
            group: "{{ openldap_server_user }}"

      - name: Copy slapd initial config changes file to system
        template:
            src: config.ldif.j2
            dest: "{{ openldap_server_app_path }}/slapd.d/config.ldif"
            mode: 0640

      - name: Configure LDAP protocol, URI and port
        lineinfile:
            path: /etc/default/slapd
            regexp: "^SLAPD_SERVICES="
            line: SLAPD_SERVICES="ldap://{{ openldap_server }}/ ldaps:/// ldapi:///"

      ### systemctl
      - name: Create dir to enable TLS for slapd service
        file:
            path: /etc/systemd/system/slapd.service.d
            recurse: true

      - name: Enable TLS for slapd service
        template:
            src: override.conf.j2
            dest: /etc/systemd/system/slapd.service.d/override.conf

      - name: Start the slapd service
        systemd:
            name: slapd
            state: restarted
            enabled: true
            daemon_reload: true

      - name: Initialize ldap config pass 1
        command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -c -f {{ openldap_server_app_path }}/slapd.d/config.ldif
        register: ldap_new_config_pass1
        changed_when: "'modifying entry' in ldap_new_config_pass1.stdout or 'adding new entry' in ldap_new_config_pass1.stdout"
        failed_when: >
            ldap_new_config_pass1.rc != 0 and
            'Already exists (68)' not in ldap_new_config_pass1.stderr and
            'Type or value exists (20)' not in ldap_new_config_pass1.stderr and
            'objectClass: value #0 invalid per syntax' not in ldap_new_config_pass1.stderr

      - name: Restart slapd service after ldap config pass 1
        systemd:
            name: slapd
            state: restarted
            daemon_reload: true

      - name: Initialize ldap config pass 2
        command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -c -f {{ openldap_server_app_path }}/slapd.d/config.ldif
        register: ldap_new_config_pass2
        changed_when: "'modifying entry' in ldap_new_config_pass2.stdout or 'adding new entry' in ldap_new_config_pass2.stdout"
        failed_when: >
            ldap_new_config_pass2.rc != 0 and
            'Already exists (68)' not in ldap_new_config_pass2.stderr and
            'Type or value exists (20)' not in ldap_new_config_pass2.stderr

  become: true
  when: installation_mode == "new"

- name: include upgrade script
  import_tasks: run-upgrades.yml
  when: "installation_mode == 'upgrade'"

- block:
      - name: Add the OS specific varibles
        include_vars: "{{ ansible_os_family }}.yml"

      - name: Install the openldap and required Packages
        package:
            name: "{{ item }}"
            state: present
        loop: "{{ openldap_server_pkgs }}"

      - name: Create directory for ldap pid
        file:
            path: "/var/run/slapd"
            state: directory
            owner: "{{ openldap_server_user }}"
            group: "{{ openldap_server_user }}"

      - name: Configure LDAP protocol, URI and port
        lineinfile:
            path: /etc/default/slapd
            regexp: "^SLAPD_SERVICES="
            line: SLAPD_SERVICES="ldap://{{ openldap_server }}/ ldaps:/// ldapi:///"

      - name: Copy slapd config changes file to system
        template:
            src: config.ldif.j2
            dest: "{{ openldap_server_app_path }}/slapd.d/config.ldif"
            mode: 0640

      - name: Create dir to enable TLS for slapd service
        file:
            path: /etc/systemd/system/slapd.service.d
            recurse: true

      - name: Enable TLS for slapd service
        template:
            src: override.conf.j2
            dest: /etc/systemd/system/slapd.service.d/override.conf

      - name: Start the slapd service
        systemd:
            name: slapd
            state: restarted
            enabled: true
            daemon_reload: true

      - name: Apply ldap config updates during upgrade pass 1
        command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -c -f {{ openldap_server_app_path }}/slapd.d/config.ldif
        register: ldap_upgrade_config_pass1
        failed_when: >
            ldap_upgrade_config_pass1.rc != 0 and
            'Already exists (68)' not in ldap_upgrade_config_pass1.stderr and
            'Type or value exists (20)' not in ldap_upgrade_config_pass1.stderr and
            'objectClass: value #0 invalid per syntax' not in ldap_upgrade_config_pass1.stderr
        changed_when: "'modifying entry' in ldap_upgrade_config_pass1.stdout or 'adding new entry' in ldap_upgrade_config_pass1.stdout"

      - name: Restart slapd service after ldap config pass 1
        systemd:
            name: slapd
            state: restarted
            daemon_reload: true

      - name: Apply ldap config updates during upgrade pass 2
        command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -c -f {{ openldap_server_app_path }}/slapd.d/config.ldif
        register: ldap_upgrade_config_pass2
        failed_when: >
            ldap_upgrade_config_pass2.rc != 0 and
            'Already exists (68)' not in ldap_upgrade_config_pass2.stderr and
            'Type or value exists (20)' not in ldap_upgrade_config_pass2.stderr
        changed_when: "'modifying entry' in ldap_upgrade_config_pass2.stdout or 'adding new entry' in ldap_upgrade_config_pass2.stdout"
  become: true
  when: installation_mode == "upgrade"
