/*
Created			29.04.2005
Last modified	10.11.2020
Project			Firewall Orchestrator
Company			Cactus eSecurity GmbH
Database		PostgreSQL 9-12
*/

/* Create Alternate Keys */
Alter Table "object" add Constraint "obj_altkey" UNIQUE ("mgm_id","zone_id","obj_uid","obj_create");
Alter Table "rule" add Constraint "rule_altkey" UNIQUE ("mgm_id","rule_uid","rule_create");
Alter Table "service" add Constraint "svc_altkey" UNIQUE ("mgm_id","svc_uid","svc_create");
Alter Table "stm_dev_typ" add Constraint "Alter_Key1" UNIQUE ("dev_typ_name","dev_typ_version");
Alter Table "zone" add Constraint "Alter_Key10" UNIQUE ("mgm_id","zone_name");
Alter Table "usr" add Constraint "usr_altkey" UNIQUE ("mgm_id","user_name","user_create");
Alter Table "changelog_object" add Constraint "alt_key_changelog_object" UNIQUE ("abs_change_id");
Alter Table "changelog_service" add Constraint "alt_key_changelog_service" UNIQUE ("abs_change_id");
Alter Table "changelog_user" add Constraint "alt_key_changelog_user" UNIQUE ("abs_change_id");
Alter Table "changelog_rule" add Constraint "alt_key_changelog_rule" UNIQUE ("abs_change_id");
Alter Table "temp_filtered_rule_ids" add Constraint "temp_filtered_rule_ids_alt_key" UNIQUE ("report_id","rule_id");
Alter Table "temp_mgmid_importid_at_report_time" add Constraint "Alter_Key13" UNIQUE ("control_id","mgm_id","report_id");
Alter Table "import_changelog" add Constraint "Alter_Key14" UNIQUE ("import_changelog_nr","control_id");



/* Create Indexes */
Create unique index "firewall_akey" on "device" using btree ("mgm_id","dev_id");
Create index "kunden_akey" on "tenant" using btree ("tenant_name");
Create unique index "kundennetze_akey" on "tenant_network" using btree ("tenant_net_id","tenant_id");
Create unique index "management_akey" on "management" using btree ("mgm_name","tenant_id");
Create index "rule_index" on "rule" using btree ("mgm_id","rule_id","rule_uid","dev_id");
Create unique index "rule_from_unique_index" on "rule_from" using btree ("rule_id","obj_id","user_id");
Create unique index "stm_color_akey" on "stm_color" using btree ("color_name");
Create index "stm_fw_typ_a2key" on "stm_dev_typ" using btree ("dev_typ_name");
Create unique index "stm_fw_typ_akey" on "stm_dev_typ" using btree ("dev_typ_name","dev_typ_version");
Create index "stm_nattypes_akey" on "stm_nattyp" using btree ("nattyp_name");
Create unique index "stm_obj_typ_akey" on "stm_obj_typ" using btree ("obj_typ_name");
Create index "import_control_start_time_idx" on "import_control" using btree ("start_time");
Create index "rule_oder_idx" on "rule_order" using btree ("control_id","rule_id");


/* Create Foreign Keys */
Alter table "uiuser" add foreign key ("uiuser_language") references "language" ("name") on update restrict on delete cascade;
Alter table "report_viewable_by_tenant" add foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Alter table "report_viewable_by_tenant" add foreign key ("report_id") references "report" ("report_id") on update restrict on delete cascade;
Alter table "report_viewable_by_user" add foreign key ("uiuser_id") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Alter table "report_viewable_by_user" add foreign key ("report_id") references "report" ("report_id") on update restrict on delete cascade;
Alter table "report" add foreign key ("report_file_id") references "report_file" ("report_file_id") on update restrict on delete cascade;

Alter table "txt" add foreign key ("language") references "language" ("name") on update restrict on delete cascade;
Create index "IX_relationship11" on "object" ("obj_nat_install");
Alter table "object" add  foreign key ("obj_nat_install") references "device" ("dev_id") on update restrict on delete cascade;
Create index "IX_Relationship126" on "rule_order" ("dev_id");
Alter table "rule_order" add  foreign key ("dev_id") references "device" ("dev_id") on update restrict on delete cascade;
Create index "IX_Relationship128" on "changelog_rule" ("dev_id");
Alter table "changelog_rule" add  foreign key ("dev_id") references "device" ("dev_id") on update restrict on delete cascade;
Create index "IX_Relationship186" on "rule" ("dev_id");
Alter table "rule" add  foreign key ("dev_id") references "device" ("dev_id") on update restrict on delete cascade;
Create index "IX_Relationship205" on "report" ("dev_id");
Alter table "report" add  foreign key ("dev_id") references "device" ("dev_id") on update restrict on delete cascade;
Create index "IX_relationship7" on "device" ("tenant_id");
Alter table "device" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_relationship15" on "tenant_object" ("tenant_id");
Alter table "tenant_object" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_relationship3" on "tenant_network" ("tenant_id");
Alter table "tenant_network" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_relationship4" on "management" ("tenant_id");
Alter table "management" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_relationship32" on "rule_review" ("tenant_id");
Alter table "rule_review" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship135" on "tenant_user" ("tenant_id");
Alter table "tenant_user" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship148" on "request" ("tenant_id");
Alter table "request" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship165" on "usr" ("tenant_id");
Alter table "usr" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship180" on "tenant_username" ("tenant_id");
Alter table "tenant_username" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship188" on "uiuser" ("tenant_id");
Alter table "uiuser" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship193" on "reporttyp_tenant_map" ("tenant_id");
Alter table "reporttyp_tenant_map" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_Relationship206" on "report" ("tenant_id");
Alter table "report" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Create index "IX_relationship5" on "device" ("mgm_id");
Alter table "device" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_relationship8" on "object" ("mgm_id");
Alter table "object" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_relationship21" on "rule" ("mgm_id");
Alter table "rule" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_relationship17" on "service" ("mgm_id");
Alter table "service" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship38" on "zone" ("mgm_id");
Alter table "zone" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship43" on "usr" ("mgm_id");
Alter table "usr" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship127" on "changelog_rule" ("mgm_id");
Alter table "changelog_rule" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship129" on "changelog_user" ("mgm_id");
Alter table "changelog_user" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship130" on "changelog_object" ("mgm_id");
Alter table "changelog_object" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship131" on "changelog_service" ("mgm_id");
Alter table "changelog_service" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_Relationship184" on "temp_mgmid_importid_at_report_time" ("mgm_id");
Alter table "temp_mgmid_importid_at_report_time" add  foreign key ("mgm_id") references "management" ("mgm_id") on update restrict on delete cascade;
Create index "IX_relationship16" on "tenant_object" ("obj_id");
Alter table "tenant_object" add  foreign key ("obj_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_relationship13" on "objgrp" ("objgrp_id");
Alter table "objgrp" add  foreign key ("objgrp_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_relationship14" on "objgrp" ("objgrp_member_id");
Alter table "objgrp" add  foreign key ("objgrp_member_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_relationship26" on "rule_from" ("obj_id");
Alter table "rule_from" add  foreign key ("obj_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_relationship28" on "rule_to" ("obj_id");
Alter table "rule_to" add  foreign key ("obj_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_Relationship65" on "changelog_object" ("old_obj_id");
Alter table "changelog_object" add  foreign key ("old_obj_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_Relationship66" on "changelog_object" ("new_obj_id");
Alter table "changelog_object" add  foreign key ("new_obj_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_Relationship105" on "objgrp_flat" ("objgrp_flat_id");
Alter table "objgrp_flat" add  foreign key ("objgrp_flat_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_Relationship106" on "objgrp_flat" ("objgrp_flat_member_id");
Alter table "objgrp_flat" add  foreign key ("objgrp_flat_member_id") references "object" ("obj_id") on update restrict on delete cascade;
Create index "IX_relationship25" on "rule_from" ("rule_id");
Alter table "rule_from" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_relationship31" on "rule_review" ("rule_id");
Alter table "rule_review" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_relationship29" on "rule_service" ("rule_id");
Alter table "rule_service" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_relationship27" on "rule_to" ("rule_id");
Alter table "rule_to" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_Relationship72" on "changelog_rule" ("new_rule_id");
Alter table "changelog_rule" add  foreign key ("new_rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_Relationship73" on "changelog_rule" ("old_rule_id");
Alter table "changelog_rule" add  foreign key ("old_rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_Relationship97" on "rule_order" ("rule_id");
Alter table "rule_order" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_Relationship182" on "temp_filtered_rule_ids" ("rule_id");
Alter table "temp_filtered_rule_ids" add  foreign key ("rule_id") references "rule" ("rule_id") on update restrict on delete cascade;
Create index "IX_relationship30" on "rule_service" ("svc_id");
Alter table "rule_service" add  foreign key ("svc_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_relationship19" on "svcgrp" ("svcgrp_id");
Alter table "svcgrp" add  foreign key ("svcgrp_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_relationship20" on "svcgrp" ("svcgrp_member_id");
Alter table "svcgrp" add  foreign key ("svcgrp_member_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_Relationship74" on "changelog_service" ("new_svc_id");
Alter table "changelog_service" add  foreign key ("new_svc_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_Relationship75" on "changelog_service" ("old_svc_id");
Alter table "changelog_service" add  foreign key ("old_svc_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_Relationship118" on "svcgrp_flat" ("svcgrp_flat_id");
Alter table "svcgrp_flat" add  foreign key ("svcgrp_flat_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_Relationship119" on "svcgrp_flat" ("svcgrp_flat_member_id");
Alter table "svcgrp_flat" add  foreign key ("svcgrp_flat_member_id") references "service" ("svc_id") on update restrict on delete cascade;
Create index "IX_relationship23" on "rule" ("action_id");
Alter table "rule" add  foreign key ("action_id") references "stm_action" ("action_id") on update restrict on delete cascade;
Create index "IX_relationship12" on "object" ("obj_color_id");
Alter table "object" add  foreign key ("obj_color_id") references "stm_color" ("color_id") on update restrict on delete cascade;
Create index "IX_relationship18" on "service" ("svc_color_id");
Alter table "service" add  foreign key ("svc_color_id") references "stm_color" ("color_id") on update restrict on delete cascade;
Create index "IX_Relationship52" on "usr" ("user_color_id");
Alter table "usr" add  foreign key ("user_color_id") references "stm_color" ("color_id") on update restrict on delete cascade;
Create index "IX_relationship6" on "device" ("dev_typ_id");
Alter table "device" add  foreign key ("dev_typ_id") references "stm_dev_typ" ("dev_typ_id") on update restrict on delete cascade;
Create index "IX_Relationship83" on "management" ("dev_typ_id");
Alter table "management" add  foreign key ("dev_typ_id") references "stm_dev_typ" ("dev_typ_id") on update restrict on delete cascade;
Create index "IX_relationship10" on "object" ("nattyp_id");
Alter table "object" add  foreign key ("nattyp_id") references "stm_nattyp" ("nattyp_id") on update restrict on delete cascade;
Create index "IX_relationship9" on "object" ("obj_typ_id");
Alter table "object" add  foreign key ("obj_typ_id") references "stm_obj_typ" ("obj_typ_id") on update restrict on delete cascade;
Create index "IX_relationship24" on "rule" ("track_id");
Alter table "rule" add  foreign key ("track_id") references "stm_track" ("track_id") on update restrict on delete cascade;
Create index "IX_Relationship33" on "service" ("ip_proto_id");
Alter table "service" add  foreign key ("ip_proto_id") references "stm_ip_proto" ("ip_proto_id") on update restrict on delete cascade;
Create index "IX_Relationship36" on "service" ("svc_typ_id");
Alter table "service" add  foreign key ("svc_typ_id") references "stm_svc_typ" ("svc_typ_id") on update restrict on delete cascade;
Create index "IX_Relationship37" on "object" ("zone_id");
Alter table "object" add  foreign key ("zone_id") references "zone" ("zone_id") on update restrict on delete cascade;
Create index "IX_Relationship90" on "rule" ("rule_from_zone");
Alter table "rule" add  foreign key ("rule_from_zone") references "zone" ("zone_id") on update restrict on delete cascade;
Create index "IX_Relationship91" on "rule" ("rule_to_zone");
Alter table "rule" add  foreign key ("rule_to_zone") references "zone" ("zone_id") on update restrict on delete cascade;
Create index "IX_Relationship50" on "usergrp" ("usergrp_id");
Alter table "usergrp" add  foreign key ("usergrp_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship51" on "usergrp" ("usergrp_member_id");
Alter table "usergrp" add  foreign key ("usergrp_member_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship79" on "changelog_user" ("new_user_id");
Alter table "changelog_user" add  foreign key ("new_user_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship80" on "changelog_user" ("old_user_id");
Alter table "changelog_user" add  foreign key ("old_user_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship95" on "rule_from" ("user_id");
Alter table "rule_from" add  foreign key ("user_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship134" on "tenant_user" ("user_id");
Alter table "tenant_user" add  foreign key ("user_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship149" on "usergrp_flat" ("usergrp_flat_id");
Alter table "usergrp_flat" add  foreign key ("usergrp_flat_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship150" on "usergrp_flat" ("usergrp_flat_member_id");
Alter table "usergrp_flat" add  foreign key ("usergrp_flat_member_id") references "usr" ("user_id") on update restrict on delete cascade;
Create index "IX_Relationship59" on "import_service" ("control_id");
Alter table "import_service" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship60" on "import_object" ("control_id");
Alter table "import_object" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship61" on "import_rule" ("control_id");
Alter table "import_rule" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship62" on "import_user" ("control_id");
Alter table "import_user" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship68" on "changelog_object" ("control_id");
Alter table "changelog_object" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship76" on "changelog_service" ("control_id");
Alter table "changelog_service" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship77" on "changelog_user" ("control_id");
Alter table "changelog_user" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship78" on "changelog_rule" ("control_id");
Alter table "changelog_rule" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship96" on "rule_order" ("control_id");
Alter table "rule_order" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship107" on "objgrp_flat" ("import_created");
Alter table "objgrp_flat" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship108" on "objgrp_flat" ("import_last_seen");
Alter table "objgrp_flat" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship120" on "objgrp" ("import_created");
Alter table "objgrp" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship121" on "objgrp" ("import_last_seen");
Alter table "objgrp" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship122" on "svcgrp" ("import_created");
Alter table "svcgrp" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship123" on "svcgrp" ("import_last_seen");
Alter table "svcgrp" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship124" on "svcgrp_flat" ("import_created");
Alter table "svcgrp_flat" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship125" on "svcgrp_flat" ("import_last_seen");
Alter table "svcgrp_flat" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship132" on "import_zone" ("control_id");
Alter table "import_zone" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship151" on "usergrp_flat" ("import_created");
Alter table "usergrp_flat" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship152" on "usergrp_flat" ("import_last_seen");
Alter table "usergrp_flat" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship153" on "usergrp" ("import_created");
Alter table "usergrp" add  foreign key ("import_created") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship154" on "usergrp" ("import_last_seen");
Alter table "usergrp" add  foreign key ("import_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship166" on "rule" ("rule_create");
Alter table "rule" add  foreign key ("rule_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship167" on "rule" ("rule_last_seen");
Alter table "rule" add  foreign key ("rule_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship168" on "rule_from" ("rf_create");
Alter table "rule_from" add  foreign key ("rf_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship169" on "rule_from" ("rf_last_seen");
Alter table "rule_from" add  foreign key ("rf_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship170" on "rule_to" ("rt_create");
Alter table "rule_to" add  foreign key ("rt_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship171" on "rule_to" ("rt_last_seen");
Alter table "rule_to" add  foreign key ("rt_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship172" on "rule_service" ("rs_create");
Alter table "rule_service" add  foreign key ("rs_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship173" on "rule_service" ("rs_last_seen");
Alter table "rule_service" add  foreign key ("rs_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship174" on "object" ("obj_create");
Alter table "object" add  foreign key ("obj_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship175" on "object" ("obj_last_seen");
Alter table "object" add  foreign key ("obj_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship176" on "service" ("svc_create");
Alter table "service" add  foreign key ("svc_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship177" on "service" ("svc_last_seen");
Alter table "service" add  foreign key ("svc_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship178" on "zone" ("zone_create");
Alter table "zone" add  foreign key ("zone_create") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship179" on "zone" ("zone_last_seen");
Alter table "zone" add  foreign key ("zone_last_seen") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship183" on "temp_mgmid_importid_at_report_time" ("control_id");
Alter table "temp_mgmid_importid_at_report_time" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship185" on "import_changelog" ("control_id");
Alter table "import_changelog" add  foreign key ("control_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship202" on "report" ("start_import_id");
Alter table "report" add  foreign key ("start_import_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship203" on "report" ("stop_import_id");
Alter table "report" add  foreign key ("stop_import_id") references "import_control" ("control_id") on update restrict on delete cascade;
Create index "IX_Relationship136" on "request_object_change" ("log_obj_id");
Alter table "request_object_change" add  foreign key ("log_obj_id") references "changelog_object" ("log_obj_id") on update restrict on delete cascade;
Create index "IX_Relationship63" on "changelog_object" ("import_admin");
Alter table "changelog_object" add  foreign key ("import_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship69" on "changelog_service" ("import_admin");
Alter table "changelog_service" add  foreign key ("import_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship70" on "changelog_user" ("import_admin");
Alter table "changelog_user" add  foreign key ("import_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship71" on "changelog_rule" ("import_admin");
Alter table "changelog_rule" add  foreign key ("import_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship109" on "changelog_object" ("doku_admin");
Alter table "changelog_object" add  foreign key ("doku_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship110" on "changelog_service" ("doku_admin");
Alter table "changelog_service" add  foreign key ("doku_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship111" on "changelog_user" ("doku_admin");
Alter table "changelog_user" add  foreign key ("doku_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship112" on "changelog_rule" ("doku_admin");
Alter table "changelog_rule" add  foreign key ("doku_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship159" on "object" ("last_change_admin");
Alter table "object" add  foreign key ("last_change_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship161" on "rule" ("last_change_admin");
Alter table "rule" add  foreign key ("last_change_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship162" on "service" ("last_change_admin");
Alter table "service" add  foreign key ("last_change_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship163" on "usr" ("last_change_admin");
Alter table "usr" add  foreign key ("last_change_admin") references "uiuser" ("uiuser_id") on update restrict on delete cascade;
Create index "IX_Relationship81" on "error_log" ("error_id");
Alter table "error_log" add  foreign key ("error_id") references "error" ("error_id") on update restrict on delete cascade;
Create index "IX_Relationship139" on "request_service_change" ("log_svc_id");
Alter table "request_service_change" add  foreign key ("log_svc_id") references "changelog_service" ("log_svc_id") on update restrict on delete cascade;
Create index "IX_Relationship145" on "request_user_change" ("log_usr_id");
Alter table "request_user_change" add  foreign key ("log_usr_id") references "changelog_user" ("log_usr_id") on update restrict on delete cascade;
Create index "IX_Relationship142" on "request_rule_change" ("log_rule_id");
Alter table "request_rule_change" add  foreign key ("log_rule_id") references "changelog_rule" ("log_rule_id") on update restrict on delete cascade;
Create index "IX_Relationship93" on "usr" ("usr_typ_id");
Alter table "usr" add  foreign key ("usr_typ_id") references "stm_usr_typ" ("usr_typ_id") on update restrict on delete cascade;
Create index "IX_Relationship194" on "reporttyp_tenant_map" ("report_typ_id");
Alter table "reporttyp_tenant_map" add  foreign key ("report_typ_id") references "stm_report_typ" ("report_typ_id") on update restrict on delete cascade;
Create index "IX_Relationship201" on "report" ("report_typ_id");
Alter table "report" add  foreign key ("report_typ_id") references "stm_report_typ" ("report_typ_id") on update restrict on delete cascade;
Create index "IX_Relationship137" on "request_object_change" ("request_id");
Alter table "request_object_change" add  foreign key ("request_id") references "request" ("request_id") on update restrict on delete cascade;
Create index "IX_Relationship140" on "request_service_change" ("request_id");
Alter table "request_service_change" add  foreign key ("request_id") references "request" ("request_id") on update restrict on delete cascade;
Create index "IX_Relationship143" on "request_rule_change" ("request_id");
Alter table "request_rule_change" add  foreign key ("request_id") references "request" ("request_id") on update restrict on delete cascade;
Create index "IX_Relationship146" on "request_user_change" ("request_id");
Alter table "request_user_change" add  foreign key ("request_id") references "request" ("request_id") on update restrict on delete cascade;
Create index "IX_Relationship155" on "changelog_object" ("change_type_id");
Alter table "changelog_object" add  foreign key ("change_type_id") references "stm_change_type" ("change_type_id") on update restrict on delete cascade;
Create index "IX_Relationship156" on "changelog_service" ("change_type_id");
Alter table "changelog_service" add  foreign key ("change_type_id") references "stm_change_type" ("change_type_id") on update restrict on delete cascade;
Create index "IX_Relationship157" on "changelog_user" ("change_type_id");
Alter table "changelog_user" add  foreign key ("change_type_id") references "stm_change_type" ("change_type_id") on update restrict on delete cascade;
Create index "IX_Relationship158" on "changelog_rule" ("change_type_id");
Alter table "changelog_rule" add  foreign key ("change_type_id") references "stm_change_type" ("change_type_id") on update restrict on delete cascade;
Create index "IX_Relationship181" on "request" ("request_type_id");
Alter table "request" add  foreign key ("request_type_id") references "request_type" ("request_type_id") on update restrict on delete cascade;

Alter table "tenant_to_device" add  foreign key ("tenant_id") references "tenant" ("tenant_id") on update restrict on delete cascade;
Alter table "tenant_to_device" add  foreign key ("device_id") references "device" ("dev_id") on update restrict on delete cascade;
