#! /bin/sh
# the following section is needed for Debian >= squeeze
### BEGIN INIT INFO
# Provides:             fworch-import
# Required-Start:       $postgres
# Required-Stop:        $postgres
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    fworch Import
### END INIT INFO

IMPORTER_PATH=/usr/local/fworch/importer
IMPORTER_BASENAME=fworch-importer-main.pl
IMPORTER_SINGLE=fworch-importer-single.pl
IMPORTER_BIN=$IMPORTER_PATH/$IMPORTER_BASENAME

if [ -x $IMPORTER_BIN ]
then
        echo ""
else
        echo "ERROR: $IMPORTER_BIN does not exist or is not executable"
        exit 5
fi

test -x $IMPORTER_BIN || exit 5

case "$1" in
    start)
        if [ `pidof -x $IMPORTER_BASENAME | wc -l` -eq 0 ]
        then
                echo "Starting fworch Import process ..."
                /bin/su -l -c "(cd $IMPORTER_PATH; $IMPORTER_BIN) >/dev/null 2>&1 &" fworch
                $0 status
        else
                echo -n "ERROR: import already running"
                $0 status
        fi
        ;;
    stop)
        echo -n "Shutting down ITSecorg Import process ... "
        if [ `pidof -x $IMPORTER_BASENAME | wc -l` -gt 0 ]
        then
                kill `pidof -x $IMPORTER_BASENAME` #>/dev/null
                if [ `pidof -x $IMPORTER_SINGLE | wc -l` -gt 0 ]
                then
                        echo "waiting for running imports to finish"
                        $0 status
                        while [ `pidof -x $IMPORTER_SINGLE | wc -l` -gt 0  ]
                        do
                                sleep 5
                        done
                        fi
        fi
                $0 status
        # do not kill currently running import (fworch-importer-single.pl)
        ;;
    status)
        if [ `pidof -x $IMPORTER_BASENAME | wc -l` -eq 0 ]
        then
                echo "no import processes are running"
        else
                echo "the following import processes are running: "
                pidof -x $IMPORTER_BASENAME
                pidof -x $IMPORTER_SINGLE
        fi
        echo ""
        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start
        ;;
    install)
        ## create links in rcX.d
        script_abs_path=`readlink -f $0`
        script_basename=`basename $(readlink -f $0)`        
        cp $script_abs_path /etc/init.d/
        /bin/ln -s /etc/init.d/$script_basename /etc/rc2.d/S88$script_basename
        /bin/ln -s /etc/init.d/$script_basename /etc/rc3.d/S88$script_basename
        /bin/ln -s /etc/init.d/$script_basename /etc/rc0.d/K22$script_basename
        /bin/ln -s /etc/init.d/$script_basename /etc/rc6.d/K22$script_basename
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        ;;
esac
