DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fwo_ro') THEN
        CREATE ROLE fwo_ro WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
    END IF;
END
$$;


GRANT CONNECT ON DATABASE fworchdb TO fwo_ro;

GRANT USAGE ON SCHEMA compliance TO fwo_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA compliance TO fwo_ro;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA compliance TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA compliance GRANT SELECT ON TABLES TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA compliance GRANT USAGE, SELECT ON SEQUENCES TO fwo_ro;

GRANT USAGE ON SCHEMA modelling TO fwo_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA modelling TO fwo_ro;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA modelling TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA modelling GRANT SELECT ON TABLES TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA modelling GRANT USAGE, SELECT ON SEQUENCES TO fwo_ro;

GRANT USAGE ON SCHEMA public TO fwo_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO fwo_ro;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO fwo_ro;

GRANT USAGE ON SCHEMA request TO fwo_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA request TO fwo_ro;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA request TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA request GRANT SELECT ON TABLES TO fwo_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA request GRANT USAGE, SELECT ON SEQUENCES TO fwo_ro;
