- block: 

  - name: remove local copy of remote config file
    file:
      state: absent
      name: "temp_remote_config_file.json"

  - name: create symlink /usr/local/fworch/etc to /etc/fworch
    file:
      src: "{{ fworch_home }}/etc"
      dest: "/etc/{{ product_name }}"
      state: link

  - name: set config values
    set_fact:
      config_json:
        product_version: "{{ product_version }}"
        fworch_home: "{{ fworch_home }}"
        dotnet_mode: "{{ dotnet_mode }}" 
        api_uri: "https://{{ api_network_listening_ip_address }}:{{ api_web_port }}/api/v1/graphql"
        api_hasura_jwt_alg: "{{ api_hasura_jwt_alg }}"
        middleware_native_uri: "http://{{ middleware_hostname }}:{{ middleware_internal_port }}/"
        middleware_uri: "{{ middleware_uri }}"
        tls_client_certificate: "{{ internalca_client_certificate }}"
        tls_client_private_key: "{{ internalca_client_private_key }}"
        tls_ca_certificate: "{{ internalca_peer_ca_certificate }}"
        remote_addresses: []

  - name: create central conf file by dumping varibale as json file
    copy: 
      content: "{{ config_json | to_nice_json }}" 
      dest: "{{ fworch_conf_file }}"
      owner: "{{ fworch_user }}"
      group: "{{ fworch_group }}"
      mode: "0640"
    when: installation_mode == "new"

  - name: Read existing configuration during upgrade
    slurp:
      src: "{{ fworch_conf_file }}"
    register: existing_config_json
    when: installation_mode == "upgrade"

  - name: Add TLS identity paths during upgrade
    copy:
      content: >-
        {{
          (
            existing_config_json.content | b64decode | from_json
          ) | combine(
            {
              'tls_client_certificate': internalca_client_certificate,
              'tls_client_private_key': internalca_client_private_key,
              'tls_ca_certificate': internalca_peer_ca_certificate
            }
          ) | to_nice_json
        }}
      dest: "{{ fworch_conf_file }}"
      owner: "{{ fworch_user }}"
      group: "{{ fworch_group }}"
      mode: "0640"
    when: installation_mode == "upgrade"

  become: true
