- name: install apache and make all global configs (non-server dependent)
  block:
    - name: Install apache2 and wsgi module
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "{{ webserver_package_name }}"
        - "{{ wsgi_package_name }}"

    - name: edit conf file for global security settings - ServerTokens
      lineinfile:
        path: "{{ apache_global_settings_file }}"
        line: ServerTokens Prod
        regexp: '^\s*ServerTokens'
        create: true
        mode: "0644"

    - name: edit conf file for global security settings - ServerSignature
      lineinfile:
        path: "{{ apache_global_settings_file }}"
        line: ServerSignature Off
        regexp: '^\s*ServerSignature'
        create: true
        mode: "0644"

    - name: edit conf file for global security settings - TraceEnable
      lineinfile:
        path: "{{ apache_global_settings_file }}"
        line: TraceEnable Off
        regexp: '^\s*TraceEnable'
        create: true
        mode: "0644"

    - name: enable global security settings
      command: "a2enconf security"

    - name: remove duplicate FWO custom apache listener lines during upgrade
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^\s*Listen {{ item }}\s*$'
        state: absent
      loop:
        - "{{ middleware_web_listener_port }}"
        - "{{ api_web_port }}"
      when: installation_mode == "upgrade"

    - name: restart apache
      service:
        name: "{{ webserver_package_name }}"
        state: restarted
      when: installation_mode != "upgrade"

  become: true
