---
# this script will uninstall all fworch components from all hosts in the chosen inventory
# call with:
# sudo ansible-playbook/ scripts/uninstall-fworch.yml -K [-e "wipe_packages=yes"]
# parameters:
# wipe_packages=yes    removes all packages potentially installed during fworch installation
#                      NB: this might break other applications running on the same system
#
# caveat: run this script with "wipe_packages" switch only if you are on an fworch-exclusive system

- name: stop docker container
  command: docker stop fworch-api
  ignore_errors: true

- name: remove docker container
  command: docker rm fworch-api
  ignore_errors: true

- name: restart postgres to make sure no connections are blocking the database removal
  service:
    name: postgresql
    state: restarted
  when: ansible_facts['distribution']|lower == 'debian' or ansible_facts['distribution']|lower == 'ubuntu'
  ignore_errors: true

- name: find out installed postgres version
  script: "scripts/get_pg_version.sh"
  register: pg_version_result
  changed_when: false

- name: set fact pg_version
  set_fact:
      pg_version: "{{ pg_version_result.stdout }}"
  ignore_errors: true

- set_fact:
    postgresql_dev_package: "{{ postgresql_dev_package_prefix }}-{{ pg_version }}"
  ignore_errors: true

# postgres operations with postgres user and ignoring errors
- block:

  - name: remove database pre pg_version 13
    postgresql_db:
      name: fworchdb
      state: absent
    register: drop_db
    when: pg_version|int < 13

  - name: remove database for pg_version starting from 13
    command: psql -c 'drop database if exists fworchdb with ( force )'
    register: drop_db
    when: pg_version|int >= 13

  - name: check if db still exists
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: "select exists(SELECT datname FROM pg_catalog.pg_database WHERE lower(datname) = lower('fworchdb'))"
    register: db_exists

  - name: fail when db still exists
    fail:
      msg: database could not be dropped {{ drop_db.msg }}. Try to stop all sessions connected to the database before running uninstall again.
    when: db_exists|bool

  - name: remove db groups
    postgresql_user:
      name: "{{ item }}"
      state: absent
    loop: "{{ database_groups }}"

  - name: remove db users
    postgresql_user:
      name: "{{ item }}"
      state: absent
    loop: "{{ database_users }}"

  become: true
  become_user: postgres
  ignore_errors: true

- name: stop and disable slapd
  service:
    name: slapd
    state: stopped
    enabled: no
  when: ansible_facts['distribution']|lower == 'debian' or ansible_facts['distribution']|lower == 'ubuntu'
  ignore_errors: true

- name: stop and disable {{ product_name }}-ui
  service:
    name: "{{ product_name }}-ui"
    state: stopped
    enabled: no
  ignore_errors: true

- name: stop and disable {{ product_name }}-middleware
  service:
    name: "{{ product_name }}-middleware"
    state: stopped
    enabled: no
  ignore_errors: true

- name: stop and disable hasura-docker-api
  service:
    name: hasura-docker-api
    state: stopped
    enabled: no
  ignore_errors: true

- block:
    - name: disable apache sites
      command: a2dissite {{ product_name }}-ui
      ignore_errors: true

    - name: disable apache modules (due to a bug with php mod not properly getting purged)
      apache2_module: state=absent name={{ item }}
      loop:
        - php
        - proxy_http
        - rewrite
        - proxy_wstunnel
      ignore_errors: true

    - name: uninstall all packages for {{ product_name }}, keeping git and ansible
      package:
        state: absent
        name: "{{ item }}"
        purge: yes
      loop:
        - rsyslog
        - apache2
        - gnupg2
        - apt-transport-https
        - software-properties-common
        - npm
        - python3-pip
        - python3-virtualenv
        - python3-psycopg2
        - libpq-dev
        - "{{ postgresql_package }}"
        - libpq-dev
        - postgresql-client
        - ldap-utils
        - libldap-common
        - libldap
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - dotnet-sdk-3.1
        - make
        - "{{ postgresql_dev_package }}"
        - "{{ postgresql_test_package }}"
        - apache2
        - libdbi-perl
        - libdbd-pg-perl
        - libdate-calc-perl
        - psmisc
        - libnet-cidr-perl
        - libsys-syslog-perl
        - libexpect-perl
        - libcgi-pm-perl
      when: wipe_packages is defined and wipe_packages|bool

    - name: uninstall openldap
      package:
        state: absent
        name: slapd
        purge: yes

    - name: remove {{ product_name }} dirs and files
      file:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ fworch_home }}"
        - /etc/{{ product_name }}
        - /etc/apache2/sites-available/{{ product_name }}-ui.conf
        - /etc/apache2/sites-available/{{ product_name }}-api.conf
        - /etc/apache2/sites-available/{{ product_name }}-mw.conf
        - /etc/apache2/sites-available/{{ product_name }}-maintenance.conf
        - /etc/apache2/sites-enabled/{{ product_name }}-ui.conf
        - /etc/apache2/sites-enabled/{{ product_name }}-api.conf
        - /etc/apache2/sites-enabled/{{ product_name }}-mw.conf
        - /etc/apache2/sites-enabled/{{ product_name }}-maintenance.conf
        - /var/lib/ldap/{{ product_name }}.internal
        - /var/lib/ldap/example.com
        - /var/lib/pgsql/data
        - "{{ api_hasura_cli_bin }}"
        - /var/{{ product_name }}
        - /var/log/{{ product_name }} 
      ignore_errors: true

    - name: remove OS users and delete home directories
      user:
        name: "{{ item }}"
        force: yes
        remove: yes
        state: absent
      loop:
        - "{{ fworch_user }}"
        - "fworchsample"

    - name: remove OS group
      group:
        name: "{{ fworch_group }}"
        state: absent

    # ssh-keygen -f "/usr/local/fworch/.ssh/known_hosts" -R "localhost"
    - name: remove known host key
      known_hosts:
        name: "localhost"
        path: "{{ fworch_home }}/.ssh/known_hosts"
        state: absent

  become: yes
