---
- block:
    - set_fact:
        ansible_user: "{{ lookup('env','USER') }}"
        os_codename: "{{ ansible_lsb.codename | lower }}"
        docker_repo_distribution: "{{ ansible_distribution | lower }}"

    # for trixie there is no docker image yet
    - set_fact:
        os_codename: bookworm
      when: "os_codename == 'trixie'"

    - name: define docker repo urls
      set_fact:
        docker_repo_base_url: "https://download.docker.com/linux/{{ docker_repo_distribution }}"
        docker_repo_release_url: "https://download.docker.com/linux/{{ docker_repo_distribution }}/dists/{{ os_codename }}/Release"

    - name: Install packages for docker download n installation
      package:
        name: "{{ item }}"
      loop:
        - gnupg2
        - apt-transport-https
        - ca-certificates
        - curl

    - name: adding docker apt signing key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        force: true
        mode: "0644"
      environment: "{{ proxy_env }}"

    - name: validate docker apt repo metadata before changing apt source
      uri:
        url: "{{ docker_repo_release_url }}"
        method: HEAD
        status_code: 200
      environment: "{{ proxy_env }}"

    - name: add docker repo
      apt_repository:
        filename: docker
        repo: "deb [arch=amd64] {{ docker_repo_base_url }} {{ os_codename }} stable"
        state: present

    - name: apt update
      apt: update_cache=true
      environment: "{{ proxy_env }}"

    - name: Install all packages for docker
      package:
        name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add the group 'docker' for {{ ansible_user }} and {{ fworch_user }} to allow running docker
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop:
        - "{{ ansible_user }}"
        - "{{ fworch_user }}"

    - name: set proxy for docker daemon to get images via proxy
      import_tasks: set-docker-daemon-proxy.yml
      notify: "docker restart"

    - name: set docker daemon bridge network
      import_tasks: set-docker-daemon-network.yml
      when: docker_network is defined and docker_network | length > 0

    - name: include upgrade script
      import_tasks: run-upgrades.yml
      when: "installation_mode == 'upgrade'"

  become: true
