---
- block:  
  - set_fact: ansible_user="{{ lookup('env','USER') }}"

  - name: Install packages for docker download n installation
    package:
      name: "{{ item }}"
    loop:
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: add apt signing key for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    environment: "{{ proxy_env }}"

  - name: add docker repo
    lineinfile:
      path: "/etc/apt/sources.list.d/docker.list"
      create: yes
      line: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"

  - name: apt update
    apt: update_cache=true
    environment: "{{ proxy_env }}"

  - name: Install all packages for docker
    package:
      name: "{{ item }}"
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
       
  - name: Add the group 'docker' for {{ ansible_user }} and {{ fworch_user }} to allow running docker
    user:
        name: "{{ item }}"
        groups: docker
        append: yes
    loop:
      -  "{{ ansible_user }}"
      -  "{{ fworch_user }}"

  # - name: create systemd dir for docker
  #   file:
  #     state: directory
  #     path: /etc/systemd/system/docker.service.d

  # - name: http-proxy-config for docker
  #   blockinfile:
  #     create: yes
  #     path:  /etc/systemd/system/docker.service.d/http-proxy.conf
  #     block: |
  #       [Service]
  #       Environment="HTTP_PROXY={{ http_proxy }}"

  - name: set proxy for docker daemon to get images via proxy
    import_tasks: set-docker-daemon-proxy.yml
    notify: "docker"

  # - name: restart docker
  #   systemd:
  #     name: docker
  #     daemon_reload: yes
  #     state: restarted
  #   become: yes

  # - name: restart service docker
  #   service:
  #     name: docker
  #     state: restarted

  # - name: Reload service systemctl
  #   systemd:
  #     daemon_reload: yes

  - name: include upgrade script
    import_tasks: run-upgrades.yml
    when: "installation_mode == 'upgrade'"

  become: yes
