
# these tasks make sure that the docker daemon can fetch images via proxy

- name: make sure docker service dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"
  become: yes
  notify: docker

- name: create docker config file for proxy settings
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    backup: yes
    create: yes
    mode: "0644"
    block: |
      [Service]
      Environment="HTTP_PROXY={{ http_proxy }}"
      Environment="HTTPS_PROXY={{ https_proxy }}"
      Environment="NO_PROXY={{ proxy_exceptions }}"
  become: yes
  notify: docker

- name: setting proxy in /etc/default/docker for eg debian
  blockinfile:
    create: yes
    path:  /etc/default/docker
    block: |
      export http_proxy="{{ http_proxy }}"
      export https_proxy="{{ https_proxy }}"
      export no_proxy={{ proxy_exceptions }}
  become: yes
  notify: docker

# these tasks make sure that the docker container can communicate via proxy
# not necessary as we already set this in hasura config

# - name: create local user docker config dir .docker
#   file:
#     dest: "{{ fworch_home }}/.docker"
#     state: directory
#     owner: "{{ fworch_user }}"
#     group: "{{ fworch_group }}"
#     mode: "0775"
#   become: yes
#   notify: docker

# - name: create local user docker config file .docker/config.json
#   template:
#     src: docker_config.j2
#     dest: "{{ fworch_home }}/.docker/config.json"
#     owner: "{{ fworch_user }}"
#     group: "{{ fworch_group }}"
#     mode: "0644"
#   become: yes
#   notify: docker



