using System.Text.Json;
using NUnit.Framework;

namespace FWO.Test
{
    /// <summary>
    /// Guards the Hasura permissions of the provisioning settings tables. The node table carries the
    /// hierarchy: a role that may rewrite a node's identity or delete the global node can detach or
    /// wipe every stored override, and the settings page refuses to load an inconsistent hierarchy.
    /// </summary>
    [TestFixture]
    [Parallelizable]
    internal class ProvisioningPermissionTest
    {
        private const string kMetadataFile = "replace_metadata.json";
        private const string kMetadataOutOfReach =
            "The Hasura metadata is not reachable in this environment, so the provisioning permissions cannot be checked.";
        private const string kPublicSchema = "public";
        private const string kNodeTable = "provisioning_config_node";
        private const string kValueTable = "provisioning_config_value";
        private const string kAuditorRole = "auditor";
        private const string kKeepGlobalNodeFilter = "{\"node_type\":{\"_neq\":\"global\"}}";

        /// <summary>Columns that identify a node or are generated by the database.</summary>
        private static readonly List<string> kNodeIdentityColumns = ["id", "node_type", "object_key"];

        private static readonly List<string> kProvisioningTables = [kNodeTable, kValueTable];

        private static readonly List<string> kWritePermissionKinds = ["insert_permissions", "update_permissions", "delete_permissions"];

        private static readonly Lazy<FileInfo?> kMetadataFileInfo = new(LocateMetadata);

        /// <summary>
        /// A node keeps its identity once created; only its place in the tree and its presentation may change.
        /// </summary>
        [Test]
        public void NodeUpdate_NeverGrantsIdentityColumns()
        {
            List<string> violations = [];
            foreach (JsonElement permission in ReadPermissions(kNodeTable, "update_permissions"))
            {
                List<string> forbidden = ReadColumns(permission).Intersect(kNodeIdentityColumns).ToList();
                if (forbidden.Count > 0)
                {
                    violations.Add($"{RoleOf(permission)} may update {string.Join(", ", forbidden)}");
                }
            }
            Assert.That(violations, Is.Empty, string.Join("; ", violations));
        }

        /// <summary>
        /// Node IDs come from the database sequence and are never chosen by a client.
        /// </summary>
        [Test]
        public void NodeInsert_NeverGrantsTheId()
        {
            List<string> violations = ReadPermissions(kNodeTable, "insert_permissions")
                .Where(permission => ReadColumns(permission).Contains("id"))
                .Select(RoleOf)
                .ToList();
            Assert.That(violations, Is.Empty, "roles that may insert a node ID: " + string.Join(", ", violations));
        }

        /// <summary>
        /// Deleting the global node would cascade to every node and override below it.
        /// </summary>
        [Test]
        public void NodeDelete_KeepsTheGlobalNode()
        {
            List<string> violations = ReadPermissions(kNodeTable, "delete_permissions")
                .Where(permission => ReadFilter(permission) != kKeepGlobalNodeFilter)
                .Select(RoleOf)
                .ToList();
            Assert.That(violations, Is.Empty, "roles that may delete the global node: " + string.Join(", ", violations));
        }

        /// <summary>
        /// The auditor may view the provisioning settings but not change them.
        /// </summary>
        [Test]
        public void Auditor_OnlyReadsTheProvisioningTables()
        {
            List<string> violations = [];
            foreach (string table in kProvisioningTables)
            {
                foreach (string kind in kWritePermissionKinds)
                {
                    if (ReadPermissions(table, kind).Any(permission => RoleOf(permission) == kAuditorRole))
                    {
                        violations.Add($"{table}.{kind}");
                    }
                }
            }
            Assert.That(violations, Is.Empty, "auditor write permissions: " + string.Join(", ", violations));
        }

        /// <summary>
        /// Skips the checks where the metadata is not deployed, because passing on no input at all
        /// would report the permissions as sound without having read them.
        /// </summary>
        [SetUp]
        public void SkipWithoutMetadata()
        {
            if (kMetadataFileInfo.Value is null)
            {
                Assert.Ignore(kMetadataOutOfReach);
            }
        }

        private static string RoleOf(JsonElement permission) => permission.GetProperty("role").GetString() ?? "";

        private static List<string> ReadColumns(JsonElement permission)
        {
            return permission.GetProperty("permission").TryGetProperty("columns", out JsonElement columns)
                ? columns.EnumerateArray().Select(column => column.GetString() ?? "").ToList()
                : [];
        }

        private static string ReadFilter(JsonElement permission)
        {
            return permission.GetProperty("permission").TryGetProperty("filter", out JsonElement filter)
                ? JsonSerializer.Serialize(filter)
                : "<none>";
        }

        /// <summary>
        /// Reads one kind of permission of a public table from the metadata file.
        /// </summary>
        /// <param name="tableName">Name of the tracked table.</param>
        /// <param name="kind">Permission kind, e.g. "update_permissions".</param>
        /// <returns>One element per role holding the permission; empty when no role holds it.</returns>
        private static List<JsonElement> ReadPermissions(string tableName, string kind)
        {
            FileInfo metadataFile = kMetadataFileInfo.Value ?? throw new InvalidOperationException(kMetadataOutOfReach);
            using JsonDocument metadata = JsonDocument.Parse(File.ReadAllText(metadataFile.FullName));

            foreach (JsonElement source in metadata.RootElement.GetProperty("args")
                .GetProperty("metadata").GetProperty("sources").EnumerateArray())
            {
                foreach (JsonElement table in source.GetProperty("tables").EnumerateArray())
                {
                    JsonElement declaration = table.GetProperty("table");
                    if (declaration.GetProperty("name").GetString() != tableName
                        || declaration.GetProperty("schema").GetString() != kPublicSchema)
                    {
                        continue;
                    }
                    if (!table.TryGetProperty(kind, out JsonElement permissions))
                    {
                        return [];
                    }
                    // Cloned, because the elements outlive the JsonDocument they were read from.
                    return permissions.EnumerateArray().Select(entry => entry.Clone()).ToList();
                }
            }
            throw new InvalidOperationException($"{kPublicSchema}.{tableName} is not tracked in {kMetadataFile}.");
        }

        /// <summary>
        /// Locates the Hasura metadata in the repository or in the directory the installer copies
        /// it to next to the tests, walking up from the directory of the test assembly.
        /// </summary>
        /// <returns>The metadata file, or null when it is out of reach.</returns>
        private static FileInfo? LocateMetadata()
        {
            DirectoryInfo? directory = new(AppContext.BaseDirectory);
            while (directory is not null)
            {
                FileInfo repository = new(Path.Combine(directory.FullName, "roles", "api", "files", kMetadataFile));
                FileInfo installed = new(Path.Combine(directory.FullName, kMetadataFile));
                if (repository.Exists)
                {
                    return repository;
                }
                if (installed.Exists)
                {
                    return installed;
                }
                directory = directory.Parent;
            }
            return null;
        }
    }
}
