using FWO.Config.Api;
using FWO.Config.Api.Data;

namespace FWO.Test
{
    internal class SimulatedGlobalConfig : GlobalConfig
    {
        public Dictionary<string, string> DummyTranslate = SimulatedUserConfig.DummyTranslate;

        public override string GetText(string key)
        {
            return DummyTranslate[key];
        }

        public SimulatedGlobalConfig() : base()
        {
            LangDict = new() { { "English", DummyTranslate } };
        }
    }

    internal class SimulatedUserConfig : UserConfig
    {
        public static Dictionary<string, string> DummyTranslate = new()
        {
            {"Rules","Rules Report"},
            {"ResolvedRules","Rules Report (resolved)"},
            {"ResolvedRulesTech","Rules Report (technical)"},
            {"UnusedRules","Unused Rules Report"},
            {"Recertification","Recertification Report"},
            {"NatRules","NAT Rules Report"},
            {"Changes","Changes Report"},
            {"ResolvedChanges","Changes Report (resolved)"},
            {"ResolvedChangesTech","Changes Report (technical)"},
            {"Connections","Connections Report"},
            {"date_of_config","Time of configuration"},
            {"generated_on","Generated on"},
            {"negated","not"},
            {"users","Users"},
            {"rule_added","Rule added"},
            {"rule_deleted","Rule deleted"},
            {"rule_modified","Rule modified"},
            {"deleted","deleted"},
            {"added","added"},
            {"missing","missing"},
            {"surplus","surplus"},
            {"change_time","Change Time"},
            {"change_type","Change Type"},
            {"number","No."},
            {"name","Name"},
            {"source_zone","Source Zone"},
            {"source","Source"},
            {"destination_zone","Destination Zone"},
            {"destination","Destination"},
            {"services","Services"},
            {"action","Action"},
            {"track","Track"},
            {"enabled","Enabled"},
            {"uid","Uid"},
            {"comment","Comment"},
            {"type","Type"},
            {"ip_address","IP Address"},
            {"members","Members"},
            {"network_objects","Network Objects"},
            {"network_services","Network Services"},
            {"protocol","Protocol"},
            {"port","Port"},
            {"next_recert_date","Next Recertification Date"},
            {"owner","Owner"},
            {"ext_app_id","External App Id"},
            {"ip_matches","IP address match"},
            {"last_hit","Last Hit"},
            {"trans_source","Translated Source"},
            {"trans_destination","Translated Destination"},
            {"trans_services","Translated Services"},
            {"from","from"},
            {"until","until"},
            {"C9001","This object was..."},
            {"C9002","This App Server was..."},
            {"C9003","App disabled"},
            {"C9004","No connections"},
            {"C9007","Requested by other owner"},
            {"C9008","Requested"},
            {"C9011","Rejected"},
            {"is_in_use","Is in use"},
            {"devices","Devices"},
            {"owners","Owners"},
            {"filter","Filter"},
            {"id","Id"},
            {"ip","Ip"},
            {"group","Group"},
            {"host","Host"},
            {"network","Network"},
            {"ip_range","IP Range"},
            {"connections","Connections"},
            {"interfaces","Interfaces"},
            {"own_common_services","Own Common Services"},
            {"global_common_services","Global Common Services"},
            {"func_reason","Functional Reason"},
            {"interface_description","Interface Description"},
            {"interface","Interface"},
            {"published","Published"},
            {"fetch_data","Fetch data"},
            {"new_connection","New Connection"},
            {"new_app_role","New AppRole: "},
            {"update_app_role","Update AppRole: "},
            {"new_svc_grp","New Servicegroup: "},
            {"add_members",": Add Members"},
            {"remove_members",": Remove Members"},
            {"new_app_zone", "New AppZone: " },
            {"update_app_zone", "Update AppZone: " },
            { "E9301", "Template File not found!" },
            { "E9302", "HTML is invalid!" },
            { "tableofcontent", "Table of content" },
            {"objects","Objects"},
            {"all","All"},
            {"report","Report"},
            {"rule", "Rule"},
            {"collapse_all","Collapse All"},
            {"clear_all", "Clear All"},
            {"used_objects", "Used Objects"},
            {"object_fetch", "Object Fetch"},
            {"app_roles", "AppRoles"},
            {"implemented", "Implemented"},
            {"not_implemented", "Not Implemented"},
            {"with_diffs", "With Diffs"},
            {"app_roles_not_implemented", "AppRoles Not Implemented"},
            {"app_roles_with_diffs", "AppRoles With Diffs"},
            {"missing_app_servers", "Missing App Servers"},
            {"surplus_app_servers", "Surplus App Servers"},
            {"VarianceAnalysis", "VarianceAnalysis"},
            {"connections_not_implemented", "Connections not implemented"},
            {"connections_with_diffs", "Connections with Diffs"},
            {"management", "Management"},
            {"gateway", "Gateway"},
            {"U1003", "In this report..."},
            {"fully_modelled", "fullymodelled"},
            {"more", "more"},
            {"AppRules", "App Rules"},
            {"change_rule", "Change Rule"},
            {"delete_rule", "Delete Rule"},
            {"impl_instructions", "Implementation Instructions"},
            {"init_environment", "Init Environment"},
            {"save_request", "Save request"},
            {"U0001", "Input text..."},
            {"on", "on"},
            {"create_rule", "Create Rule"},
            {"create_group", "Create Group"},
            {"modify_group", "Modify Group"},
            {"delete_group", "Delete Group"},
            {"promote_task", "Promote task"},
            {"modify_rule", "Modify Rule"},
            {"remove_rule", "Remove Rule"},
            {"English", "English"},
            {"last_successful", "Last successful"},
            {"common_service", "Common Service"},
            {"managements", "Managements"},
            {"load_rules", "Load Rules"},
            {"enforcing_devices", "enforcing_devices" },
            {"no_changes_found", "no_changes_found" },
            {"network_object_added", "network_object_added" },
            {"network_object_deleted", "network_object_deleted" },
            {"network_object_modified", "network_object_modified" },
            {"service_added", "service_added" },
            {"service_deleted", "service_deleted" },
            {"service_modified", "service_modified" },
            {"user_added","user_added" },
            {"user_deleted","user_deleted" },
            {"user_modified","user_modified" },
            {"interface_permission","Interface Permission" },
            {"Public","Public" },
            {"edit_connection","Edit Connection" },
            {"edit_common_service","Edit Common Service" },
            {"edit_interface","Edit Interface" },
            {"insert_forbidden","Insert forbidden" },
            {"replace","Replace" },
            {"E9017","ErrorText" },
            {"from_ticket","From Ticket" },
            {"InterfaceRejected","Interface rejected" },
            {"interface_requested","Interface requested" },
            {"requested_interfaces","Requested Interfaces" },
            {"show_removed_requested_interfaces","Show removed requested interfaces" },
            {"reject_tickets","Close Tickets as rejected" },
            {"reject_interface","Reject interface" },
            {"requesting_app","Requesting App" },
            {"requesting_ext_app_id","Requesting Ext App Id" },
            {"used_in_connection_ids","Used In Connection Ids" },
            {"requested_app","Requested App" },
            {"requested_ext_app_id","Requested Ext App Id" },
            {"requested_interface","Requested Interface" },
            {"creation_date","Creation Date" },
            {"reason","Reason" },
            {"all_open","All Open" },
            {"U9017","Are you sure you want to reject following requested interface: " },
            {"U9018","Ticket rejected." },
            {"U9036","Rejected by Admin" },
            {"state","State" },
            {"ticket","Ticket" },
            {"implementation","Implementation" },
            {"U9012","Requested Interface" },
            {"E9004","Missing Source/Destination or Service" },
            {"E9005","Source/Destination changed" },
            {"E9020","Interface in use by other app" },
            {"E5102","Missing name or reason" },
            {"E9006","Missing source/destination or service" },
            {"U9022","Network areas on other side" },
            {"U9021","Interfaces cannot use areas" },
            {"U9023","Common areas not allowed" },
            {"E9015","Insert not allowed" },
            {"select","Select" },
            {"E9021","Interface permission required" },
            {"decomm_interface","Decommission Interface" },
            {"send_email","Send Email"},
            {"U9033","Emails sent to @@OK_NUMBER@@ owners."},
            {"E9019","Email could not be sent to @@FAIL_NUMBER@@ owners."},
            {"notification","Notification" },
            {"edit_policy","Edit policy" },
            {"criteria","Criteria"},
            {"add","Add"},
            {"cancel","Cancel"},
            {"save","Save"},
            {"monitoring","Monitoring"},
            {"modelling","Modelling"},
            {"object_users","Object users"},
            {"app_role_users","App role users"},
            {"orphaned_view","Show orphaned only"},
            {"remove_all_orphans","Remove all orphans"},
            {"U7103","Remove all orphans?"},
            {"orphaned_entries_removed","Orphaned entries removed"},
            {"orphaned_app_roles","Orphaned app roles"},
            {"app_servers","App servers"},
            {"orphaned_app_servers","Orphaned app servers"},
            {"network_areas","Network areas"},
            {"orphaned_network_areas","Orphaned network areas"},
            {"service_groups","Service groups"},
            {"services_groups","Service groups"},
            {"orphaned_service_groups","Orphaned service groups"},
            {"orphaned_services","Orphaned services"},
            {"app_role","App role"},
            {"app_server","App server"},
            {"network_area","Network area"},
            {"service_group","Service group"},
            {"service","Service"},
            {"C9029","Orphaned tooltip"},
            {"U7001","Monitoring intro"},
            {"open_alerts","Open alerts"},
            {"no_open_alerts","No open alerts"},
            {"acknowledge_all","Acknowledge all"},
            {"actions","Actions"},
            {"details","Details"},
            {"acknowledge","Acknowledge"},
            {"timestamp","Timestamp"},
            {"title","Title"},
            {"code","Code"},
            {"description","Description"},
            {"remove_sample_data","Remove sample data"},
            {"U7003","Remove sample data message"},
            {"U7102","Acknowledge all message"},
            {"acknowledge_alert","Acknowledge alert"},
            {"alerts_acknowledged","alerts acknowledged"},
            {"E7015","Acknowledge failed"},
            {"confirm","Confirm"},
            {"delete","Delete"},
            {"remove","Remove"},
            {"PagerPagesize","Page size"},
            {"PagerSubmit","Apply"},
            {"loading","Loading"},
            {"in_progress","In progress"},
            {"rollback_import","Rollback import"},
            {"U5104","Rollback message start"},
            {"U5105","Rollback message end"},
            {"U5106","No import to rollback"},
            {"U5120","Some Details for modelling objects."},
            {"rollback","Rollback"},
            {"full_rollback","Full rollback"},
            {"not_imported_yet","Not imported yet"},
            {"U51XX","Import missing"},
            {"U5107","Rollback done"},
            {"import_status_details","Import status details: "},
            {"import_enabled","Import enabled"},
            {"first_import","First import"},
            {"import_id","Import id"},
            {"start","Start"},
            {"stop","Stop"},
            {"duration","Duration"},
            {"success","Success"},
            {"errors","Errors"},
            {"last_successful_import","Last successful import"},
            {"err_since_last_succ","Errors since last success"},
            {"last_import","Last import"},
            {"ok","OK"},
            {"autodiscovery","Autodiscovery"},
            {"disable","Disable"},
            {"gateways","Gateways"},
            {"nothing_more_to_change","Nothing more to change"},
            {"do_all_changes","Do all changes"},
            {"delete_management","Delete management"},
            {"delete_gateway","Delete gateway"},
            {"change_management_state","Change management state"},
            {"save_management","Save management"},
            {"save_gateway","Save gateway"},
            {"alert","Alert"},
            {"analyze_actions","Analyze actions"},
            {"E7001","Already done"},
            {"E7002","Reference missing"},
            {"E7003","Delete in progress"},
            {"E5106","Management already active"},
            {"E5107","Gateway already active"},
            {"E5112","Save gateway failed"},
            {"U5101","Delete management "},
            {"U5103","Delete gateway "},
            {"U7002","Confirm"},
            {"add_device_to_tenant0","Add device to tenant"},
            {"acknowledge_action","Acknowledge action"},
            {"C9021","Not implemented"},
            {"C9022","Variance found"},
            {"C9023","Modelling ok"},
            {"C9024","Implementation ok"},
            {"C9025","Variance not checked"},
            {"C9026","Interface decommissioned"},
            {"C9028","Interface no permission"},
            {"C9030","Foreign non production groups on used interface"},
            {"C9019","Empty service groups (interface)"},
            {"C9018","Empty service groups"},
            {"C9020","Documentation only"},
            {"C9015","Empty app roles (interface)"},
            {"C9013","Empty app roles"},
            {"C9016","Deleted objects (interface)"},
            {"C9014","Deleted objects"},
            {"modRequestOnlyOwnObjects","Request only own objects"},
            {"H5668","Request only own objects help"}
        };

        public override string GetText(string key)
        {
            return DummyTranslate[key];
        }

        public static ConfigItem[] GetAsConfigs()
        {
            List<ConfigItem> configs = [];
            foreach (var dictValuePair in DummyTranslate)
            {
                configs.Add(new() { Key = dictValuePair.Key, Value = dictValuePair.Value, User = 0 });
            }
            return [.. configs];
        }
    }
}
