using FWO.Config.Api;
using FWO.Config.Api.Data;

namespace FWO.Test
{
    internal class SimulatedGlobalConfig : GlobalConfig
    {
        public Dictionary<string, string> DummyTranslate = new(SimulatedUserConfig.DummyTranslate);
        public Dictionary<string, string> GermanTranslate = new(SimulatedUserConfig.DummyTranslate);

        public override string GetText(string key)
        {
            return GetTextInLanguage(key, DefaultLanguage);
        }

        public SimulatedGlobalConfig() : base()
        {
            LangDict = new()
            {
                { "English", DummyTranslate },
                { "German", GermanTranslate }
            };
            OverDict = new()
            {
                { "English", [] },
                { "German", [] }
            };
        }
    }

    internal class SimulatedUserConfig : UserConfig
    {
        public static Dictionary<string, string> DummyTranslate = new()
        {
            {"Rules","Rules Report"},
            {"ResolvedRules","Rules Report (resolved)"},
            {"ResolvedRulesTech","Rules Report (technical)"},
            {"UnusedRules","Unused Rules Report"},
            {"Recertification","Recertification Report"},
            {"OwnerRecertification","Owner Recertification"},
            {"Owners","Owners"},
            {"NatRules","NAT Rules Report"},
            {"Changes","Changes Report"},
            {"ResolvedChanges","Changes Report (resolved)"},
            {"ResolvedChangesTech","Changes Report (technical)"},
            {"Connections","Connections Report"},
            {"date_of_config","Time of configuration"},
            {"generated_on","Generated on"},
            {"negated","not"},
            {"users","Users"},
            {"rule_added","Rule added"},
            {"rule_deleted","Rule deleted"},
            {"rule_modified","Rule modified"},
            {"deleted","deleted"},
            {"added","added"},
            {"missing","missing"},
            {"surplus","surplus"},
            {"change_time","Change Time"},
            {"change_type","Change Type"},
            {"number","No."},
            {"name","Name"},
            {"modIntegrationStates","Integration States"},
            {"modIntegrationStateMarker","State Marker"},
            {"monitor_status","Monitor status"},
            {"monitor_status_none","None"},
            {"monitor_status_request_running","Request running"},
            {"monitor_status_implemented","Implemented"},
            {"monitor_status_rejected","Rejected"},
            {"include_into_request","Include into request"},
            {"request_fw_change","Request firewall changes"},
            {"request_running","Request running"},
            {"changes_not_requested","Changes not requested"},
            {"all_implemented","All implemented"},
            {"rejections","Rejections"},
            {"last_requested","Last Requested"},
            {"UpdateModelling","Update Modelling"},
            {"none","None"},
            {"None","None"},
            {"clean_zones","Clean zones"},
            {"designated_zone_matrix","Designated zone matrix"},
            {"H5529","Update Modelling"},
            {"H5537","Clean zones: When enabled, tasks are bundled only if their source and destination objects can be mapped to the same network zones using the selected policy matrix."},
            {"source_zone","Source Zone"},
            {"source","Source"},
            {"destination_zone","Destination Zone"},
            {"destination","Destination"},
            {"services","Services"},
            {"action","Action"},
            {"track","Track"},
            {"enabled","Enabled"},
            {"uid","Uid"},
            {"comment","Comment"},
            {"type","Type"},
            {"ip_address","IP Address"},
            {"members","Members"},
            {"current_members","Current Members"},
            {"members_to_add","Members to add"},
            {"members_to_remove","Members to remove"},
            {"duplicate_objects_more","... and @@COUNT@@ more"},
            {"requested_connections","Requested Connections"},
            {"group_requests","Group Requests"},
            {"network_objects","Network Objects"},
            {"flow_objects","Flow Objects"},
            {"flow_network_objects","Flow Network Objects"},
            {"flow_service_objects","Flow Service Objects"},
            {"flow_network_groups","Flow Network Groups"},
            {"flow_service_groups","Flow Service Groups"},
            {"flow_time_objects","Flow Time Objects"},
            {"flow","Flow"},
            {"flow_general_settings","General Settings"},
            {"flow_naming","Flow naming source ranking"},
            {"H5601","On this page the general modelling settings are administrated. This includes predefined services, display options, naming conventions and the remaining modelling settings. The extracted notifications are available on the adjacent notifications page."},
            {"H5839","Matrix violation"},
            {"H5840","Restricted Service"},
            {"H5841","Not assessable"},
            {"edit_state","Edit state"},
            {"duplicate_state_id","A workflow state with this id already exists."},
            {"save_connection","Save Connection"},
            {"by","by"},
            {"recertification","Recertification"},
            {"recertified_rules","Recertified rules"},
            {"RecertificationEvent","Recertification Event"},
            {"RecertEventReport","Recertification Event Report"},
            {"edit_notification","Edit notification"},
            {"E4010","Missing email subject"},
            {"E4011","Missing recipient"},
            {"E4012","Missing offsets"},
            {"E4013","Incomplete repetition settings"},
            {"ConfiguredResponsibles","Responsible types"},
            {"OtherAddresses","Other addresses"},
            {"Main","Main"},
            {"Supporting","Supporting"},
            {"modEnsureAtLeastOneEmailNotification","Ensure at least one notification"},
            {"email_address","Email address"},
            {"CurrentHandler","Current handler"},
            {"RecentHandler","Recent handler"},
            {"AssignedGroup","Assigned group"},
            {"Requester","Requester"},
            {"Approver","Approver"},
            {"LastCommenter","Last commenter"},
            {"add_service","Add service"},
            {"edit_service","Edit service"},
            {"protocol","Protocol"},
            {"port","Port"},
            {"save_service","Save service"},
            {"E5118","Port range invalid"},
            {"select_all","Select All"},
            {"clear_all","Clear All"},
            {"collapse_all","Collapse All"},
            {"expand_all","Expand All"},
            {"select_management","Select management"},
            {"select_visible_protocols","Select visible protocols"},
            {"archive","Archive"},
            {"report_type","Report type"},
            {"template","Template"},
            {"generation_date","Generation date"},
            {"user","User"},
            {"description","Description"},
            {"archive_truncated","Older reports exist but are not listed"},
            {"export_report","Export report"},
            {"export_report_download","Download export"},
            {"E1002","No report to export"},
            {"download_csv","Download CSV"},
            {"download_pdf","Download PDF"},
            {"download_html","Download HTML"},
            {"download_json","Download JSON"},
            {"exporting","Exporting"},
            {"download","Download"},
            {"download_failed","Downloading the file failed"},
            {"report_elements","Elements"},
            {"load","Load"},
            {"report_template","Report template"},
            {"U1002","Delete template"},
            {"report_time","Report time"},
            {"unused_days","Unused days"},
            {"diff_interval","Diff interval"},
            {"show_non_impact_rules","Show non impact rules"},
            {"tenant","Tenant"},
            {"select_device","Select device"},
            {"select_time","Select time"},
            {"report_filters","Report filters"},
            {"rule_filters","Rule filters"},
            {"save_template","Save template"},
            {"edit_template","Edit template"},
            {"delete_template","Delete template"},
            {"open","Open"},
            {"Days","Days"},
            {"Weeks","Wochen"},
            {"Months","Months"},
            {"Years","Years"},
            {"service_objects","Service Objects"},
            {"move_up","Move up"},
            {"move_down","Move down"},
            {"custom_objects","Custom Network Objects"},
            {"custom_network_objects","Custom Network Objects"},
            {"custom_service_objects","Custom Service Objects"},
            {"create_custom_network_object","Create Custom Network Object"},
            {"create_custom_service_object","Create Custom Service Object"},
            {"H5016","This page shows the flow network object catalog and the matching tools for cleanup and maintenance."},
            {"H5017","The catalog brings flow objects, duplicate mappings, and custom network objects together in one place."},
            {"H5018","Use the page to set naming sources, resolve conflicts, and create individual mappings manually when needed."},
            {"H5020","Flow name recalculation applies the selected management ranking to network objects, network groups, service objects, service groups, and time objects."},
            {"H5025","For duplicate mappings, the catalog and resolver dialog also show the technical details of the flow object. In the catalog view, long lists are shortened and finished with a note about additional objects."},
            {"network_services","Network Services"},
            {"next_recert_date","Next Recertification Date"},
            {"last_recertified","Last Recertified"},
            {"last_recertifier","Last Recertifier"},
            {"owner_recert_overview","Recertification overview"},
            {"merge_owner_recert_tables","Merge all displayed tables"},
            {"owner_additional_info_key","Additional info key"},
            {"main_responsible","Main responsible person (DN)"},
            {"owner","Owner"},
            {"ext_app_id","External App Id"},
            {"ip_matches","IP address match"},
            {"last_hit","Last Hit"},
            {"trans_source","Translated Source"},
            {"trans_destination","Translated Destination"},
            {"trans_services","Translated Services"},
            {"from","from"},
            {"until","until"},
            {"C9001","This object was..."},
            {"C9002","This App Server was..."},
            {"C9003","App disabled"},
            {"C9004","No connections"},
            {"C9007","Requested by other owner"},
            {"C9008","Requested"},
            {"C9011","Rejected"},
            {"all_readonly","all_readonly"},
            {"path_analysis","path_analysis"},
            {"rule_uid","rule_uid"},
            {"no_gws_found","no_gws_found"},
            {"flow_bundle_id","Bundle ID"},
            {"is_in_use","Is in use"},
            {"devices","Devices"},
            {"owners","Owners"},
            {"requests","Requests"},
            {"filter","Filter"},
            {"statistics","Statistics"},
            {"id","Id"},
            {"ip","Ip"},
            {"group","Group"},
            {"host","Host"},
            {"network","Network"},
            {"ip_range","IP Range"},
            {"internet_local_zone","Internet/Local"},
            {"connections","Connections"},
            {"interfaces","Interfaces"},
            {"own_common_services","Own Common Services"},
            {"global_common_services","Global Common Services"},
            {"func_reason","Functional Reason"},
            {"interface_description","Interface Description"},
            {"interface","Interface"},
            {"published","Published"},
            {"fetch_data","Fetch data"},
            {"new_connection","New Connection"},
            {"new_app_role","New AppRole: "},
            {"update_app_role","Update AppRole: "},
            {"new_svc_grp","New Servicegroup: "},
            {"add_members",": Add Members"},
            {"remove_members",": Remove Members"},
            {"new_app_zone", "New AppZone: " },
            {"update_app_zone", "Update AppZone: " },
            { "E9301", "Template File not found!" },
            { "E9302", "HTML is invalid!" },
            { "tableofcontent", "Table of content" },
            {"objects","Objects"},
            {"all","All"},
            {"oneTaskForAllDevices","One task for all devices"},
            {"report","Report"},
            {"rule", "Rule"},
            {"used_objects", "Used Objects"},
            {"object_fetch", "Object Fetch"},
            {"app_roles", "AppRoles"},
            {"implemented", "Implemented"},
            {"not_implemented", "Not Implemented"},
            {"with_diffs", "With Diffs"},
            {"app_roles_not_implemented", "AppRoles Not Implemented"},
            {"app_roles_with_diffs", "AppRoles With Diffs"},
            {"missing_app_servers", "Missing App Servers"},
            {"surplus_app_servers", "Surplus App Servers"},
            {"VarianceAnalysis", "VarianceAnalysis"},
            {"connections_not_implemented", "Connections not implemented"},
            {"connections_with_diffs", "Connections with Diffs"},
            {"management", "Management"},
            {"gateway", "Gateway"},
            {"U1003", "In this report..."},
            {"fully_modelled", "fullymodelled"},
            {"more", "more"},
            {"AppRules", "App Rules"},
            {"change_rule", "Change Rule"},
            {"delete_rule", "Delete Rule"},
            {"impl_instructions", "Implementation Instructions"},
            {"init_environment", "Init Environment"},
            {"save_request", "Save request"},
            {"daily_recert_check", "Daily recertification check"},
            {"daily_importer_check", "Daily importer check"},
            {"daily_sample_data_check", "Daily sample data check"},
            {"sample_data", "Sample data"},
            {"sample_data_found_in", "Sample data found in "},
            {"no_sample_data_found", "No sample data found"},
            {"import", "Import"},
            {"import_credential", "Import credentials"},
            {"tenants", "Tenants"},
            {"groups", "Groups"},
            {"import_issues_found", " import issues found"},
            {"no_import_issues_found", "No import issues found"},
            {"E7011", "Import running too long"},
            {"E7012", "No import"},
            {"E7013", "Successful import overdue"},
            {"U0001", "Input text..."},
            {"on", "on"},
            {"create_rule", "Create Rule"},
            {"create_group", "Create Group"},
            {"modify_group", "Modify Group"},
            {"delete_group", "Delete Group"},
            {"promote_task", "Promote task"},
            {"modify_rule", "Modify Rule"},
            {"remove_rule", "Remove Rule"},
            {"English", "English"},
            {"last_successful", "Last successful"},
            {"common_service", "Common Service"},
            {"edit", "Edit"},
            {"managements", "Managements"},
            {"enforcing_devices", "enforcing_devices" },
            {"no_changes_found", "no_changes_found" },
            {"network_object_added", "network_object_added" },
            {"network_object_deleted", "network_object_deleted" },
            {"network_object_modified", "network_object_modified" },
            {"service_added", "service_added" },
            {"service_deleted", "service_deleted" },
            {"service_modified", "service_modified" },
            {"user_added","user_added" },
            {"user_deleted","user_deleted" },
            {"user_modified","user_modified" },
            {"interface_permission","Interface Permission" },
            {"Public","Public" },
            {"edit_connection","Edit Connection" },
            {"edit_common_service","Edit Common Service" },
            {"edit_interface","Edit Interface" },
            {"insert_forbidden","Insert forbidden" },
            {"replace","Replace" },
            {"E9017","ErrorText" },
            {"from_ticket","From Ticket" },
            {"InterfaceRejected","Interface rejected" },
            {"interface_requested","Interface requested" },
            {"requested_interfaces","Requested Interfaces" },
            {"show_removed_requested_interfaces","Show removed requested interfaces" },
            {"show_import_deactivated_requested_interfaces","Show interface requests of import-deactivated owners" },
            {"show_lifecycle_deactivated_requested_interfaces","Show interface requests of owners with inactive lifecycle state" },
            {"requesting_owner_state","Requesting Owner State" },
            {"requested_owner_state","Requested Owner State" },
            {"owner_import_deactivated","Import deactivated" },
            {"owner_lifecycle_deactivated","Inactive lifecycle state" },
            {"reject_tickets","Close Tickets as rejected" },
            {"close_as_done","Close as done" },
            {"close_tickets_as_done","Close Tickets as done" },
            {"reject","Reject" },
            {"orphaned_requested_interface_tickets","Open tickets with requested interface problems" },
            {"orphaned_requested_interface_tickets_empty","No open tickets with requested interface problems were found." },
            {"connection_id","Connection ID" },
            {"problem_reason","Problem reason" },
            {"E9022","Duplicate-looking open interface request" },
            {"E9023","Missing connection ID" },
            {"E9024","Requested interface not found" },
            {"E9025","Linked connection is not a requested interface" },
            {"E9026","Ticket and connection link mismatch" },
            {"E9027","Requested interface removed" },
            {"E9028","Requested interface is already published" },
            {"E9029","Ticket has multiple request tasks" },
            {"H7423","If requested interface problems still have open tickets, the administrator can close those tickets together as rejected." },
            {"H7424","The button \"Open tickets with requested interface problems\" opens a separate list of all still open new-interface tickets whose requested interface linkage is missing, broken, removed, already published, or suspicious. The check is performed only when opening the popup, so it is independent from the current table filter. Depending on the problem, tickets can be closed as rejected or as done." },
            {"reject_interface","Reject interface" },
            {"requesting_app","Requesting App" },
            {"requesting_ext_app_id","Requesting Ext App Id" },
            {"used_in_connection_ids","Used In Connection Ids" },
            {"requested_app","Requested App" },
            {"requested_ext_app_id","Requested Ext App Id" },
            {"requested_interface","Requested Interface" },
            {"display_ticket","Display Ticket" },
            {"ext_ticket_number","External ticket number" },
            {"group_create","Create Group" },
            {"group_modify","Modify Group" },
            {"group_delete","Delete Group" },
            {"creation_date","Creation Date" },
            {"reason","Reason" },
            {"all_open","All Open" },
            {"U9017","Are you sure you want to reject following requested interface: " },
            {"U9018","Ticket rejected." },
            {"U9036","Rejected by Admin" },
            {"U9038","Closed as done by Admin" },
            {"U9039","Ticket closed as done." },
            {"U9040","Are you sure you want to close @@COUNT@@ ticket(s) as rejected?" },
            {"U9041","Are you sure you want to close @@COUNT@@ ticket(s) as done?" },
            {"state","State" },
            {"criticality","Criticality" },
            {"owner_lc_state","Production state" },
            {"additional_info","Additional Info" },
            {"active","Active" },
            {"inactive","Inactive" },
            {"ticket","Ticket" },
            {"ticket_id","Ticket Id" },
            {"tasks","Tasks" },
            {"requester","Requester" },
            {"reference_date","Reference date" },
            {"U4003","Overdue owners" },
            {"U4004","No overdue owners." },
            {"U4005","Owners due within @@DAYS@@ days" },
            {"U4006","No owners due within @@DAYS@@ days." },
            {"U4007","Further active owners" },
            {"U4008","Further owners" },
            {"U4009","Owners with inactive recertification" },
            {"no_recertifiable_owners_assigned","No recertifiable owners assigned." },
            {"C1003","Merge all recertification tables displayed in the report into one table." },
            {"C1004","Select a key from the owner additional information and choose whether the value is only displayed, filtered by existence, filtered by non-existence, or matched as an exact value." },
            {"created","Created" },
            {"closed","Closed" },
            {"task_number","Task Number" },
            {"start_time","Start Time" },
            {"end_time","End Time" },
            {"implementation","Implementation" },
            {"approval","Approval" },
            {"opened","Opened" },
            {"approved","Approved" },
            {"U9012","Requested Interface" },
            {"E9004","Missing Source/Destination or Service" },
            {"E9005","Source/Destination changed" },
            {"E9020","Interface in use by other app" },
            {"E5102","Missing name or reason" },
            {"E9006","Missing source/destination or service" },
            {"U9022","Network areas on other side" },
            {"U9021","Interfaces cannot use areas" },
            {"U9023","Common areas not allowed" },
            {"E9015","Insert not allowed" },
            {"select","Select" },
            {"E9021","Interface permission required" },
            {"decomm_interface","Decommission Interface" },
            {"send_email","Send Email"},
            {"confirm_sent_mail","Confirm sent email via UI message"},
            {"confirm_modelling_update","Confirm modelling update via UI message"},
            {"modelling_objects_updated"," modelling objects updated"},
            {"H5530","Confirm sent email via UI message: After successful sending, the action shows a UI message with the number of sent emails."},
            {"H5534","Confirm modelling update via UI message: After a successful update, the action shows a UI message with the number of updated modelling objects."},
            {"emails_sent"," emails sent"},
            {"U9033","Emails sent to @@OK_NUMBER@@ owners."},
            {"E9019","Email could not be sent to @@FAIL_NUMBER@@ owners."},
            {"notification","Notification" },
            {"edit_policy","Edit policy" },
            {"criteria","Criteria"},
            {"add","Add"},
            {"cancel","Cancel"},
            {"change_default","Change default"},
            {"save","Save"},
            {"api_ticket_initial_state","API ticket initial state"},
            {"use_default","Use default"},
            {"H5546","API tickets: Here the optional initial state for tickets created via the API is defined. If no state is set, the default start state is still used."},
            {"monitoring","Monitoring"},
            {"modelling","Modelling"},
            {"modelling_general_settings","General Settings"},
            {"notifications","Notifications"},
            {"request_interface","Request Interface"},
            {"reminders","Reminders"},
            {"decommission","Decommission"},
            {"modReqInterfaceName","Name of requested interface"},
            {"modReqEmailRequesterInCc","Requester in CC"},
            {"modReqEmailReceiver","Receiver of request email"},
            {"modReqEmailSubject","Subject of request emails"},
            {"modReqEmailBody","Body of request emails"},
            {"modUnansweredReqEmailBody","Body of unanswered request emails"},
            {"modReqTicketTitle","Title of interface request ticket"},
            {"modReqTaskTitle","Title of interface request task"},
            {"modDecommEmailReceiver","Receiver of decommission email"},
            {"modDecommEmailSubject","Subject of decommission emails"},
            {"modDecommEmailBody","Body of decommission emails"},
            {"object_users","Object users"},
            {"app_role_users","App role users"},
            {"orphaned_view","Show orphaned only"},
            {"remove_all_orphans","Remove all orphans"},
            {"U7103","Remove all orphans?"},
            {"orphaned_entries_removed","Orphaned entries removed"},
            {"orphaned_app_roles","Orphaned app roles"},
            {"app_servers","App servers"},
            {"orphaned_app_servers","Orphaned app servers"},
            {"network_areas","Network areas"},
            {"orphaned_network_areas","Orphaned network areas"},
            {"service_groups","Service Groups"},
            {"services_groups","Service groups"},
            {"orphaned_service_groups","Orphaned service groups"},
            {"orphaned_services","Orphaned services"},
            {"app_role","App role"},
            {"app_server","App server"},
            {"network_area","Network area"},
            {"service_group","Service group"},
            {"service","Service"},
            {"C9029","Orphaned tooltip"},
            {"U7001","Monitoring intro"},
            {"open_alerts","Open alerts"},
            {"no_open_alerts","No open alerts"},
            {"acknowledge_all","Acknowledge all"},
            {"actions","Actions"},
            {"details","Details"},
            {"acknowledge","Acknowledge"},
            {"timestamp","Timestamp"},
            {"title","Title"},
            {"code","Code"},
            {"remove_sample_data","Remove sample data"},
            {"U7003","Remove sample data message"},
            {"U7102","Acknowledge all message"},
            {"acknowledge_alert","Acknowledge alert"},
            {"alerts_acknowledged","alerts acknowledged"},
            {"E7015","Acknowledge failed"},
            {"confirm","Confirm"},
            {"delete","Delete"},
            {"remove","Remove"},
            {"close","Close"},
            {"PagerPagesize","Page size"},
            {"PagerSubmit","Apply"},
            {"loading","Loading"},
            {"in_progress","In progress"},
            {"rollback_import","Rollback import"},
            {"U5104","Rollback message start"},
            {"U5105","Rollback message end"},
            {"U5106","No import to rollback"},
            {"U5120","Some Details for modelling objects."},
            {"rollback","Rollback"},
            {"full_rollback","Full rollback"},
            {"not_imported_yet","Not imported yet"},
            {"U51XX","Import missing"},
            {"U5107","Rollback done"},
            {"import_status_details","Import status details: "},
            {"import_enabled","Import enabled"},
            {"first_import","First import"},
            {"import_id","Import id"},
            {"start","Start"},
            {"stop","Stop"},
            {"duration","Duration"},
            {"success","Success"},
            {"errors","Errors"},
            {"last_successful_import","Last successful import"},
            {"err_since_last_succ","Errors since last success"},
            {"last_import","Last import"},
            {"ok","OK"},
            {"autodiscovery","Autodiscovery"},
            {"disable","Disable"},
            {"gateways","Gateways"},
            {"nothing_more_to_change","Nothing more to change"},
            {"do_all_changes","Do all changes"},
            {"delete_management","Delete management"},
            {"delete_gateway","Delete gateway"},
            {"change_management_state","Change management state"},
            {"save_management","Save management"},
            {"save_gateway","Save gateway"},
            {"alert","Alert"},
            {"analyze_actions","Analyze actions"},
            {"E7001","Already done"},
            {"E7002","Reference missing"},
            {"E7003","Delete in progress"},
            {"E5106","Management already active"},
            {"E5107","Gateway already active"},
            {"E5121","Please enter a name for the custom flow object"},
            {"E5122","Please select at least one service"},
            {"E5123","Selected services must share the same protocol and port range"},
            {"E5112","Save gateway failed"},
            {"U5101","Delete management "},
            {"U5103","Delete gateway "},
            {"U7002","Confirm"},
            {"add_device_to_tenant0","Add device to tenant"},
            {"acknowledge_action","Acknowledge action"},
            {"C9021","Not implemented"},
            {"C9022","Variance found"},
            {"C9023","Modelling ok"},
            {"C9024","Implementation ok"},
            {"C9025","Variance not checked"},
            {"C9026","Interface decommissioned"},
            {"C9028","Interface no permission"},
            {"C9030","Foreign non production groups on used interface"},
            {"C9031","You need the recertifier role to recertify this owner."},
            {"C9032","You are not assigned to this owner as a recertifiable responsible person."},
            {"C9019","Empty service groups (interface)"},
            {"C9018","Empty service groups"},
            {"C9020","Documentation only"},
            {"C9015","Empty app roles (interface)"},
            {"C9013","Empty app roles"},
            {"C9016","Deleted objects (interface)"},
            {"C9014","Deleted objects"},
            {"TicketReport","Ticket Report"},
            {"TicketChangeReport","Ticket Change Report"},
            {"workflow_filters","Workflow Filters"},
            {"other_filters","Other filters"},
            {"variance_filters","Variance Filters"},
            {"add_info","Add. Info"},
            {"rules_for_deleted_conns","Rules from deleted connections"},
            {"analyse_remaining_rules","Analyse remaining rules"},
            {"task_type","Task type"},
            {"phase","Phase"},
            {"label","Label"},
            {"existing","existing"},
            {"not_existing","not existing"},
            {"value","value"},
            {"display_only","Display only"},
            {"TicketCreation","Ticket creation"},
            {"TicketClosure","Ticket closure"},
            {"ApprovalOpened","Approval opened"},
            {"Approved","Approved"},
            {"TaskStart","Task start"},
            {"TaskEnd","Task end"},
            {"ImplementationStart","Implementation start"},
            {"ImplementationEnd","Implementation end"},
            {"AnyActivity","Any activity"},
            {"access","access"},
            {"rule_modify","rule modify"},
            {"rule_delete","rule delete"},
            {"new_interface","new interface"},
            {"now","now"},
            {"today","today"},
            {"last","last"},
            {"day","day"},
            {"week","week"},
            {"month","month"},
            {"year","year"},
            {"modRequestOnlyOwnObjects","Request only own objects"},
            {"H5668","Request only own objects help"},
            {"change_id","Change-ID"},
            {"H1517","Reference date tooltip"},
            {"H1518","Task type tooltip"},
            {"H1519","State tooltip"},
            {"H1520","Show full ticket tooltip"},
            {"H1521","Phase tooltip"},
            {"H1525","Only for Owners report: State and Criticality: These fields restrict the displayed owners to the selected lifecycle state and selected criticality. The default value \"all\" leaves the respective filter inactive."},
            {"H1526","Only for Owner Recertification and in report templates: Add. Info selects a key from the owner additional information. In the dialog the selected key can be displayed only or used as a filter for existence, non-existence, or an exact value."},
            {"H1524","Detailed view tooltip"},
            {"detailed_view","Detailed View"},
            {"task","Task"},
            {"U9026","Nothing to request!"},
            {"CreateFlow","Create flow"},
            {"flow_creation_succeeded","Flow DB entries were created."},
            {"flow_creation_failed","Flow DB entries could not be created. Check the workflow log for unresolved objects or services."},
            {"T0100","Translated template comment"},
            {"PreferredCollapseState","Default state of the collapsible elements"},
            {"PreferredCollapseState_Collapsed","Collapsed"},
            {"PreferredCollapseState_Expanded","Expanded"},
            {"PreferredCollapseState_Intermediate","Intermediate"},
            {"edit_fix_crit","Edit fixed criterion"},
            {"H5512","Criterion help"},
            {"content_mode","Content mode"},
            {"elements","Elements"},
            {"content","Content"},
            {"criterion_hint_minimum_cidr_length","CIDR hint"},
            {"criterion_hint_forbidden_service_uid","UID hint"},
            {"criterion_hint_forbidden_service_protocol_port","Port/protocol hint"},
            {"criterion_hint_forbid_source_name","Source name hint"},
            {"criterion_hint_forbid_destination_name","Destination name hint"},
            {"criterion_error_minimum_cidr_length","Invalid CIDR"},
            {"criterion_error_forbidden_service_protocol_port","Invalid port protocol"},
            {"criterion_error_non_empty_content","Content required"},
            {"criterion_no_content_required","No content required"},
            {"port_protocol","Port/Protocol"},
            {"edit_app_server","edit_app_server"},
            {"delete_app_server","delete_app_server"},
            {"reactivate","reactivate"},
            {"U9005","Reactivate "},
            {"U9007","Cannot delete used "},
            {"U9008","Delete "},
            {"U9004","Delete "},
            {"execute_selected","Execute selected"},
            {"report_data_fetch","Report data fetch"},
            {"no_device_selected","No device selected"},
            {"E1001","No device selected"},
            {"E1003","Canceled"},
            {"generate_report","Generate report"},
            {"E4002","No rules found"},
            {"E4001","Comment required"},
            {"E9104","You are not allowed to execute selected rules."},
            {"recerts_executed","Recerts executed "},
            {"decerts_executed","Decerts executed "},
            {"load_rules","Load rules"},
            {"stop_fetching","Stop fetching"},
            {"add_comment","Add comment"},
            {"language_settings","Language settings"},
            {"personal_settings","Personal settings"},
            {"display_settings","Display settings"},
            {"U5412","Select the UI language"},
            {"apply_changes","Apply changes"},
            {"change_language","Change language"},
            {"customize_texts","Customize texts"},
            {"U5321","Customize the UI texts"},
            {"search","Search"},
            {"case_sensitive","Case sensitive"},
            {"ignore_helptexts","Ignore help texts"},
            {"key","Key"},
            {"text","Text"},
            {"custom_text","Custom text"},
            {"U5301","Custom texts saved"},
            {"H5702","Select language"},
            {"H5703","Search texts"},
            {"H5704","Results"},
            {"email_settings","Email settings"},
            {"U5319","Email settings intro"},
            {"email_enc_method","Encryption"},
            {"email_auth_user","Auth user"},
            {"email_auth_pwd","Auth password"},
            {"email_sender","Sender"},
            {"use_dummy_email_address","Use dummy email"},
            {"dummy_email_address","Dummy email"},
            {"read_config","Read Config"},
            {"save_email_conn","Save email connection"},
            {"E5301","Error reading or processing Config."},
            {"E5103","Invalid port"},
            {"E5108","Invalid sender address"},
            {"test_email_connection","Test email connection"},
            {"test_connection","Test connection"},
            {"E8101","No user email configured"},
            {"U5402","Email connection OK"},
            {"readonly_credential","Credentials"},
            {"U5116","Credential settings"},
            {"add_new_credential","Add credential"},
            {"is_key_pair","Key pair"},
            {"edit_credential","Edit credential"},
            {"private_key","Private key"},
            {"public_key","Public key"},
            {"login_secret","Login secret"},
            {"cloud_client_id","Cloud client id"},
            {"cloud_client_secret","Cloud client secret"},
            {"fetch_credentials","Fetch credentials"},
            {"save_credential","Save credential"},
            {"delete_credential","Delete credential"},
            {"E5117","Credential is used by managements"},
            {"U5117","Delete credential "},
            {"U5108","Remove sample credentials"},
            {"U5214","Group settings"},
            {"group_action","Group action"},
            {"user_action","User action"},
            {"add_new_group","Add group"},
            {"edit_group","Edit group"},
            {"assign_user","Assign user"},
            {"remove_user","Remove user"},
            {"owner_group","Owner group"},
            {"roles","Roles"},
            {"save_group","Save group"},
            {"assign_user_to_group","Assign user to group"},
            {"remove_user_from_group","Remove user from group"},
            {"fetch_groups","Fetch groups"},
            {"fetch_roles","Fetch roles"},
            {"E5231","Failed to fetch groups"},
            {"E5234","Missing group name"},
            {"E5235","Duplicate group name"},
            {"E5236","Add group failed"},
            {"E5237","Edit group failed"},
            {"E5238","Group has users"},
            {"E5239","Delete group failed"},
            {"E5240","Missing user or group"},
            {"E5241","Duplicate user"},
            {"E5242","Add user failed"},
            {"E5243","Remove user failed"},
            {"E5244","Missing DN"},
            {"E5245","Sample data still in use"},
            {"U5204","Delete group "},
            {"U5205","Delete sample data"},
            {"E5251","No roles found"},
            {"assign_user_group_to_role","Assign user/group to role"},
            {"E5246","Add group to role failed"},
            {"ldap_conns","LDAP connections"},
            {"U5211","LDAP connections overview"},
            {"add_new_ldap","Add LDAP"},
            {"edit_ldap","Edit LDAP"},
            {"tenant_level","Tenant level"},
            {"pattern_length","Pattern length"},
            {"user_search_path","User search path"},
            {"role_search_path","Role search path"},
            {"group_search_path","Group search path"},
            {"group_write_path","Group write path"},
            {"search_user","Search user"},
            {"search_user_pwd","Search user password"},
            {"write_user","Write user"},
            {"write_user_pwd","Write user password"},
            {"global_tenant_name","Global tenant name"},
            {"fetch_ldap_conn","Fetch LDAP connections"},
            {"save_ldap_conn","Save LDAP connection"},
            {"delete_ldap_conn","Delete LDAP connection"},
            {"E5204","LDAP load failed"},
            {"E5261","Only one LDAP exists"},
            {"E5262","Role handling prevents delete"},
            {"E5266","LDAP is reachable"},
            {"E5267","LDAP test failed"},
            {"E5268","LDAP auth failed"},
            {"E5269","LDAP bind failed"},
            {"E5270","LDAP certificate failed"},
            {"E5263","Invalid pattern length"},
            {"E5264","Duplicate LDAP endpoint"},
            {"E5265","Role handling requires internal LDAP"},
            {"E5260","Cannot deactivate the last active LDAP"},
            {"E5201","Adding LDAP failed"},
            {"E5202","Updating LDAP failed"},
            {"U5111","Managements overview"},
            {"add_new_management","Add management"},
            {"autodiscover","Autodiscover"},
            {"readonly_credential_mgm","Readonly credential"},
            {"config_path","Config path"},
            {"super_manager","Super manager"},
            {"importer_host","Importer host"},
            {"debug_level","Debug level"},
            {"edit_management","Edit management"},
            {"fetch_managements","Fetch managements"},
            {"manual_autodiscovery","Manual autodiscovery"},
            {"changes_found"," changes found"},
            {"found_no_changes","No changes found"},
            {"ran_into_exception","Ran into exception: "},
            {"U5102","Delete sample managements"},
            {"E5101","Management has devices"},
            {"E5104","Invalid debug level"},
            {"E5105","Duplicate management"},
            {"E5109","Invalid legacy management name"},
            {"U5112","Gateway settings"},
            {"add_new_gateway","Add gateway"},
            {"edit_gateway","Edit gateway"},
            {"fetch_gateways","Fetch gateways"},
            {"change_password","Change Password"},
            {"old_password","Old Password"},
            {"new_password","New Password"},
            {"U5401","Password changed."},
            {"U5411","Change the password for the current user"},
            {"password_policy","Password Policy"},
            {"U5312","Set the policy for all user passwords"},
            {"pwMinLength","Min Length"},
            {"pwUpperCaseRequired","Upper Case Required"},
            {"pwLowerCaseRequired","Lower Case Required"},
            {"pwNumberRequired","Number Required"},
            {"pwSpecialCharactersRequired","Special Characters Required"},
            {"change_policy","Change Password Policy"},
            {"U5302","Policy changed."},
            {"U5215","Role assignments"},
            {"assign_user_group","Assign user/group"},
            {"remove_user_group","Remove user/group"},
            {"users_groups","Users/groups"},
            {"remove_user_group_from_role","Remove user/group from role"},
            {"user_group","User/group"},
            {"E5254","Duplicate assignment"},
            {"E5255","Assignment failed"},
            {"E5256","Admin role must keep one user"},
            {"E5257","Removal failed"},
            {"E5258","Missing DN"},
            {"owner_lifecycle_states","Owner Lifecycle States"},
            {"add_owner_lc_state","Add Owner Lifecycle State"},
            {"edit_owner_lc_state","Edit Owner Lifecycle State"},
            {"delete_owner_lc_state","Delete Owner Lifecycle State"},
            {"U5219","Are you sure you want to delete Owner Lifecycle State: "}
        };

        public override string GetText(string key)
        {
            return DummyTranslate.TryGetValue(key, out string? value) ? value : key;
        }

        public static ConfigItem[] GetAsConfigs()
        {
            List<ConfigItem> configs = [];
            foreach (var dictValuePair in DummyTranslate)
            {
                configs.Add(new() { Key = dictValuePair.Key, Value = dictValuePair.Value, User = 0 });
            }
            return [.. configs];
        }
    }
}
