# database_dir: /var/lib/pgsql/data
postgresql_package: postgresql
postgresql_test_package: pgtap
postgresql_c_client_library_header_files: libpq-dev
postgresql_dev_package_prefix: postgresql-server-dev
database_install_dir: "{{ fworch_home }}/database"
fwo_db_ro_user: fwo_ro

# table_space variable can be used to create database in another place where there is enough space
# table_space: /var/db/fworch_tablespace
# table_space_name: fworch

db_schemata:
  - compliance
  - modelling
  - public
  - request

database_users:
  - dbbackup
  - fworchimporter

database_groups:
  - dbbackupusers
  - configimporters
  - fworchadmins


database_idempotent_files:
  - fworch-api-funcs.sql
  - fworch-backup-grants.sql
  - fworch-encryption.sql
  - fworch-path-analysis.sql
  - fworch-rule-recert.sql
  - fworch-texts.sql
  - fworch-views-changes.sql
