
sample_config_user: fworchsample
# sample_config_user_home: "/home/{{ sample_config_user }}"
sample_data_rate: medium
sample_role_purpose: demo
sample_fortigate_basename: fortigate
sample_fortigate_name: "{{ sample_fortigate_basename }}_demo"
sample_fortigate_dev_uid: FortiWiFiFirewall
sample_checkpoint_basename: "checkpoint"
sample_checkpoint_name: "{{ sample_checkpoint_basename }}_demo"
sample_checkpoint_uri: "https://fwodemodata.cactus.de/demo17_cpr8x_v{{ product_version.split('.') | first }}.json"
demo_cpr8x_name_without_demo: "CPR81"
demo_cpr8x_name: "{{ demo_cpr8x_name_without_demo}}_demo"
demo_cpr8x_uri: "https://fwodemodata.cactus.de/demo17_cpr8x_v{{ product_version.split('.') | first }}.json"
demo_cpr8x_mgm_uid: "041d28f5-bb5f-4f46-bb1c-217ccf272278"
demo_cpr8x_dev1_uid: "11372f6c-fcda-49b0-8576-910c6804d53c"
demo_cpr8x_dev2_uid: "4d18802a-4dff-4a43-abea-f2bdf9f6ce8f"
demo_fos_name_without_demo: "FortiOS"
demo_fos_name: "{{ demo_fos_name_without_demo }}_demo"
demo_fos_uri: "https://fwodemodata.cactus.de/demo16_fortios_lab.json"
sample_postfix: _demo

# sample openldap server
second_ldap_db: no
sample_ldap_path: "dc=example,dc=com"
sample_ldap_domain_name: example.com
sample_ldap_superuser_name: "cn=Manager,ou=user,{{ sample_ldap_path }}"
