
name: Build

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
    - 'documentation/**'
    - 'design/**'

  pull_request:
    types: [ ready_for_review, review_requested ]
    branches: [ main, develop ]
    paths-ignore:
    - 'documentation/**'
    - 'design/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_ubuntu_latest:
    name: test build on ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - name: Set up dependencies for Chromium
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       libgdk-pixbuf2.0-0 \
    #       libx11-xcb1 \
    #       libfontconfig1 \
    #       libx11-6 \
    #       libasound2 \
    #       libatk-bridge2.0-0 \
    #       libatk1.0-0 \
    #       libcups2 \
    #       libdbus-1-3 \
    #       libnspr4 \
    #       libnss3 \
    #       libxcomposite1 \
    #       libxrandr2

    # - name: Check pre-installed Chromium
    #   run: which chromium-browser || which google-chrome

    # - name: Chromium version
    #   run: chromium-browser --version          

    # # - name: Set up Puppeteer
    # #   uses: googlechrome/puppeteer

    # - name: Check missing libraries
    #   run: ldd $(which chromium-browser)
  
    - name: do test install in case of merged pull request
      run: cd /home/runner/work/firewall-orchestrator/firewall-orchestrator && \
        ansible-playbook -e quicktest=true -e force_install=true site.yml -K

