name: FWO Test Install

on:
  push:
    branches:
      - main
      - develop
      - importer-rework

  pull_request:

jobs:
  test-install:
    name: Test install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      RUNNING_ON_GITHUB_ACTIONS: true
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Run Ansible test install
        run: |
          cd /home/runner/work/firewall-orchestrator/firewall-orchestrator
          ansible-playbook -e force_install=true site.yml -K

      - name: Running in GitHub actions requires testing puppeteer pdf creation separately
        if: ${{ env.RUNNING_ON_GITHUB_ACTIONS == 'true' }}
        run: |
          cd /home/runner/work/firewall-orchestrator/firewall-orchestrator/roles/tests-unit/files/FWO.Test
          dotnet restore
          dotnet build
          dotnet test --filter "Name=HtmlToPdfTest"


  python-code-check:
    name: Python Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11' 

      - run: pip install -r requirements.txt

      - uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b
        with:
          version: "0.15.0"

      - run: pyright

      - run: ruff check
      
      - run: ruff format --exit-non-zero-on-format